PLATE_MAP <-
structure(c("Anti-Cancer Agents", "Chemical Sensitivity", "Nutrient Supplements",
"Chemicals", "Chemicals", "Chemical Sensitivity", "Phosphorus and Sulfur Sources",
"Chemicals", "Anti-Cancer Agents", "Carbon and Energy Sources",
"Carbon Sources", "Identification", "Osmolytes", "Chemicals",
"Chemical Sensitivity", "Carbon Sources", "Microbial Community Analysis",
"Chemicals", "Chemical Sensitivity", "Chemicals", "Chemicals",
"Sporulating and Filamentous N2", "Sporulating and Filamentous P2",
"Chemicals", "Chemicals", "Chemical Sensitivity", "Hormones & Metabolic Effectors",
"Anti-Cancer Agents", "Anti-Cancer Agents", "Chemical Sensitivity",
"Nitrogen Sources", "Hormones & Metabolic Effectors", "Carbon and Energy Sources / Nitrogen Sources",
"Peptide Nitrogen Sources", "Peptide Nitrogen Sources", "Chemicals",
"Ions", "Carbon and Energy Sources / Nitrogen Sources", "Carbon and Energy Sources / Nitrogen Sources",
"Hormones & Metabolic Effectors", "Peptide Nitrogen Sources",
"pH"), .Names = c("PM-M14", "PM24", "PM05", "PM16", "PM14", "PM21",
"PM04", "PM15", "PM-M12", "PM-M01", "PM01", "Gen III", "PM09",
"PM20", "PM23", "PM02", "ECO", "PM17", "PM25", "PM18", "PM13",
"SF-N2", "SF-P2", "PM12", "PM19", "PM22", "PM-M06", "PM-M11",
"PM-M13", "PM-M TOX01", "PM03", "PM-M08", "PM-M02", "PM06", "PM08",
"PM11", "PM-M05", "PM-M03", "PM-M04", "PM-M07", "PM07", "PM10"
))
