WELL_MAP <-
structure(c("(+)-Catechin Hydrate", "(+)-Catechin Hydrate", "(+)-Catechin Hydrate",
"(+)-Catechin Hydrate", "Vinblastine Sulfate", "Vinblastine Sulfate",
"Vinblastine Sulfate", "Vinblastine Sulfate", "Acivicin", "Floxuridine",
"Floxuridine", "Floxuridine", "Floxuridine", "Methotrexate",
"Methotrexate", "Methotrexate", "Methotrexate", "Nocodazole",
"Acivicin", "Acivicin", "Acivicin", "Doxorubicin Hydrochloride",
"Doxorubicin Hydrochloride", "Doxorubicin Hydrochloride", "Doxorubicin Hydrochloride",
"Mitomycin C", "Podofilox", "No Chemical", "13-cis Retinoic Acid",
"Rapamycin", "4'-Demethylepipodophyllotoxin", "Cytosine-b-D-arabinofuranoside",
"Etoposide", "Quercetin Dihydrate", "Daunorubicin Hydrochloride",
"Etoposide", "Nocodazole", "Quercetin Dihydrate", "Cytosine-b-D-arabinofuranoside",
"Cytosine-b-D-arabinofuranoside", "13-cis Retinoic Acid", "13-cis Retinoic Acid",
"13-cis Retinoic Acid", "Rapamycin", "Rapamycin", "Rapamycin",
"all-trans Retinoic Acid", "Etoposide", "Etoposide", "Podofilox",
"all-trans Retinoic Acid", "Miltefosine", "Miltefosine", "Miltefosine",
"Miltefosine", "Nocodazole", "Nocodazole", "Quercetin Dihydrate",
"Quercetin Dihydrate", "Elaidylphosphocholine", "Elaidylphosphocholine",
"Elaidylphosphocholine", "Elaidylphosphocholine", "Cepharanthine",
"Cepharanthine", "Cepharanthine", "Cepharanthine", "Podofilox",
"Podofilox", "Piceatannol", "Piceatannol", "No Chemical", "Lefunomide",
"Daunorubicin Hydrochloride", "Daunorubicin Hydrochloride", "Lefunomide",
"Lefunomide", "Lefunomide", "Colchicine", "Colchicine", "Colchicine",
"Colchicine", "No Chemical", "all-trans Retinoic Acid", "4'-Demethylepipodophyllotoxin",
"4'-Demethylepipodophyllotoxin", "4'-Demethylepipodophyllotoxin",
"No Chemical", "Piceatannol", "all-trans Retinoic Acid", "Daunorubicin Hydrochloride",
"Cytosine-b-D-arabinofuranoside", "Mitomycin C", "Piceatannol",
"Mitomycin C", "Mitomycin C", "Isoniazid", "Isoniazid", "Isoniazid",
"Isoniazid", "(+)-Miconazole Nitrate", "(+)-Miconazole Nitrate",
"(+)-Miconazole Nitrate", "(+)-Miconazole Nitrate", "Pentamidine Isethionate",
"Azauracil", "Azauracil", "Azauracil", "Azauracil", "Sodium Metasilicate",
"Sodium Metasilicate", "Sodium Metasilicate", "Sodium Metasilicate",
"Propiconazole", "Pentamidine Isethionate", "Pentamidine Isethionate",
"Pentamidine Isethionate", "Aluminum Sulfate", "Aluminum Sulfate",
"Aluminum Sulfate", "Aluminum Sulfate", "Methyl Viologen", "Sodium Benzoate",
"Apramycin", "Berberine Chloride", "Thialysine", "Zaragozic Acid A",
"Sodium Fluoride", "Fluconazole", "Tamoxifen", "Cisplatin", "Fluconazole",
"Propiconazole", "Tamoxifen", "Sodium Fluoride", "Sodium Fluoride",
"Berberine Chloride", "Berberine Chloride", "Berberine Chloride",
"Thialysine", "Thialysine", "Thialysine", "EGTA", "Fluconazole",
"Fluconazole", "Sodium Benzoate", "EGTA", "Blasticidin S", "Blasticidin S",
"Blasticidin S", "Blasticidin S", "Propiconazole", "Propiconazole",
"Tamoxifen", "Tamoxifen", "Thioridazine", "Thioridazine", "Thioridazine",
"Thioridazine", "Aminacrine", "Aminacrine", "Aminacrine", "Aminacrine",
"Sodium Benzoate", "Sodium Benzoate", "Pyrophosphate", "Pyrophosphate",
"Apramycin", "Potassium Chromate", "Cisplatin", "Cisplatin",
"Potassium Chromate", "Potassium Chromate", "Potassium Chromate",
"Chlortetracycline", "Chlortetracycline", "Chlortetracycline",
"Chlortetracycline", "Apramycin", "EGTA", "Zaragozic Acid A",
"Zaragozic Acid A", "Zaragozic Acid A", "Apramycin", "Pyrophosphate",
"EGTA", "Cisplatin", "Sodium Fluoride", "Methyl Viologen", "Pyrophosphate",
"Methyl Viologen", "Methyl Viologen", "Quinolinic Acid", "Nicotinic Acid",
"Nicotinamide", "b-Nicotinamide Adenine Dinucleotide", "Tween 20",
"Tween 40", "Tween 60", "Tween 80", "(5)4-Amino-Imidazole-4(5)-Carboxamide",
"L-Ornithine", "L-Citrulline", "Chorismic Acid", "Shikimic Acid (-)",
"L-Tyrosine", "L-Valine", "L-Isoleucine + L-Valine", "4-Hydroxy-L-Proline (trans)",
"a-Keto-Butyric Acid", "Hypoxanthine", "Inosine", "2'-Deoxy-Inosine",
"Folic Acid", "Inosine + Thiamine", "Thiamine", "Thiamine Pyrophosphate",
"D-Glucose", "Guanine", "Negative Control", "Putrescine", "Cytosine",
"2'-Deoxy-Adenosine", "Thymine", "myo-Inositol", "D,L-Mevalonic Acid Lactone",
"Cyanocobalamin", "Riboflavin", "Butyric Acid", "D,L-Carnitine",
"Glutathione (reduced form)", "Thymidine", "Spermidine", "Spermine",
"Pyridoxine", "Cytidine", "D,L-Diamino-Pimelic Acid", "2'-Deoxy-Cytidine",
"b-Alanine", "Pyrrolo-Quinoline Quinone", "Menadione", "Guanosine-3',5'-Cyclic Monophosphate",
"Pyridoxamine", "L-Glutamine", "Glycine", "L-Histidine", "L-Isoleucine",
"a-Hydroxy-Butyric Acid", "Sodium Caprylate", "D,L-a-Lipoic Acid (oxidized form)",
"Choline", "L-Leucine", "L-Lysine", "L-Methionine", "L-Phenylalanine",
"L-Asparagine", "L-Aspartic Acid", "L-Cysteine", "L-Glutamic Acid",
"Guanosine", "2'-Deoxy-Guanosine", "Uridine", "2'-Deoxy-Uridine",
"Positive Control", "L-Homoserine Lactone", "p-Amino-Benzoic Acid",
"Oxaloacetic Acid", "D-Alanine", "D-Aspartic Acid", "D-Glutamic Acid",
"L-Proline", "L-Serine", "L-Threonine", "L-Tryptophan", "L-Alanine",
"D-Pantothenic Acid", "Adenosine-3',5'-Cyclic Monophosphate",
"Adenine", "Adenosine", "L-Arginine", "Orotic Acid", "Pyridoxal",
"D-Biotin", "N-Acetyl-D-Glucosamine", "d-Amino-Levulinic Acid",
"Uracil", "Hematin", "Deferoxamine Mesylate", "Potassium Tellurite",
"Potassium Tellurite", "Potassium Tellurite", "Potassium Tellurite",
"Sorbic Acid", "Sorbic Acid", "Sorbic Acid", "Sorbic Acid", "Cetylpyridinium Chloride",
"1-Chloro-2,4-Dinitrobenzene", "1-Chloro-2,4-Dinitrobenzene",
"1-Chloro-2,4-Dinitrobenzene", "1-Chloro-2,4-Dinitrobenzene",
"Protamine Sulfate", "Protamine Sulfate", "Protamine Sulfate",
"Protamine Sulfate", "Glycine Hydroxamate", "Cetylpyridinium Chloride",
"Cetylpyridinium Chloride", "Cetylpyridinium Chloride", "Ferric Chloride",
"Ferric Chloride", "Ferric Chloride", "Ferric Chloride", "Sodium Selenite",
"Trimethoprim", "Cefotaxime", "Streptomycin", "Cinoxacin", "5-Chloro-7-Iodo-8-Hydroxyquinoline",
"Aluminum Sulfate", "L-Glutamic Acid g-Hydroxamate", "Chloroxylenol",
"Chromium (III) Chloride", "L-Glutamic Acid g-Hydroxamate", "Glycine Hydroxamate",
"Chloroxylenol", "Aluminum Sulfate", "Aluminum Sulfate", "Streptomycin",
"Streptomycin", "Streptomycin", "Cinoxacin", "Cinoxacin", "Cinoxacin",
"5-Azacytidine", "L-Glutamic Acid g-Hydroxamate", "L-Glutamic Acid g-Hydroxamate",
"Trimethoprim", "5-Azacytidine", "Norfloxacin", "Norfloxacin",
"Norfloxacin", "Norfloxacin", "Glycine Hydroxamate", "Glycine Hydroxamate",
"Chloroxylenol", "Chloroxylenol", "Sulfanilamide", "Sulfanilamide",
"Sulfanilamide", "Sulfanilamide", "Phosphomycin", "Phosphomycin",
"Phosphomycin", "Phosphomycin", "Trimethoprim", "Trimethoprim",
"Rifamycin SV", "Rifamycin SV", "Cefotaxime", "Diamide", "Chromium (III) Chloride",
"Chromium (III) Chloride", "Diamide", "Diamide", "Diamide", "Dichlofluanid",
"Dichlofluanid", "Dichlofluanid", "Dichlofluanid", "Cefotaxime",
"5-Azacytidine", "5-Chloro-7-Iodo-8-Hydroxyquinoline", "5-Chloro-7-Iodo-8-Hydroxyquinoline",
"5-Chloro-7-Iodo-8-Hydroxyquinoline", "Cefotaxime", "Rifamycin SV",
"5-Azacytidine", "Chromium (III) Chloride", "Aluminum Sulfate",
"Sodium Selenite", "Rifamycin SV", "Sodium Selenite", "Sodium Selenite",
"Chloramphenicol", "Chloramphenicol", "Chloramphenicol", "Chloramphenicol",
"Sodium Orthovanadate", "Sodium Orthovanadate", "Sodium Orthovanadate",
"Sodium Orthovanadate", "Sodium Cyanate", "Cadmium Chloride",
"Cadmium Chloride", "Cadmium Chloride", "Cadmium Chloride", "1-Hydroxy-Pyridine-2-Thione",
"1-Hydroxy-Pyridine-2-Thione", "1-Hydroxy-Pyridine-2-Thione",
"1-Hydroxy-Pyridine-2-Thione", "EGTA", "Sodium Cyanate", "Sodium Cyanate",
"Sodium Cyanate", "Carbenicillin", "Carbenicillin", "Carbenicillin",
"Carbenicillin", "Piperacillin", "Sodium Arsenate", "Acriflavine",
"Cefoxitin", "Sodium Dichromate", "Sanguinarine Chloride", "Sodium Metavanadate",
"Sodium Nitrite", "Promethazine", "Chelerythrine", "Sodium Nitrite",
"EGTA", "Promethazine", "Sodium Metavanadate", "Sodium Metavanadate",
"Cefoxitin", "Cefoxitin", "Cefoxitin", "Sodium Dichromate", "Sodium Dichromate",
"Sodium Dichromate", "Nitrofurantoin", "Sodium Nitrite", "Sodium Nitrite",
"Sodium Arsenate", "Nitrofurantoin", "Aminacrine", "Aminacrine",
"Aminacrine", "Aminacrine", "EGTA", "EGTA", "Promethazine", "Promethazine",
"Fusaric Acid", "Fusaric Acid", "Fusaric Acid", "Fusaric Acid",
"Furaltadone", "Furaltadone", "Furaltadone", "Furaltadone", "Sodium Arsenate",
"Sodium Arsenate", "Sodium Metaborate", "Sodium Metaborate",
"Acriflavine", "Iodoacetic Acid", "Chelerythrine", "Chelerythrine",
"Iodoacetic Acid", "Iodoacetic Acid", "Iodoacetic Acid", "Boric Acid",
"Boric Acid", "Boric Acid", "Boric Acid", "Acriflavine", "Nitrofurantoin",
"Sanguinarine Chloride", "Sanguinarine Chloride", "Sanguinarine Chloride",
"Acriflavine", "Sodium Metaborate", "Nitrofurantoin", "Chelerythrine",
"Sodium Metavanadate", "Piperacillin", "Sodium Metaborate", "Piperacillin",
"Piperacillin", "Copper (II) Sulfate", "Copper (II) Sulfate",
"Copper (II) Sulfate", "Copper (II) Sulfate", "Zinc Chloride",
"Zinc Chloride", "Zinc Chloride", "Zinc Chloride", "L-Aspartic-b-Hydroxamate",
"1-Hydroxy-Pyridine-2-Thione", "1-Hydroxy-Pyridine-2-Thione",
"1-Hydroxy-Pyridine-2-Thione", "1-Hydroxy-Pyridine-2-Thione",
"Domiphen Bromide", "Domiphen Bromide", "Domiphen Bromide", "Domiphen Bromide",
"Diamide", "L-Aspartic-b-Hydroxamate", "L-Aspartic-b-Hydroxamate",
"L-Aspartic-b-Hydroxamate", "Nickel Chloride", "Nickel Chloride",
"Nickel Chloride", "Nickel Chloride", "Neomycin", "Protamine Sulfate",
"Guanidine Hydrochloride", "Compound 48/80", "Sodium Dichromate",
"Promethazine", "D-Cycloserine", "Trifluoperazine", "Thiourea",
"Sodium Selenite", "Trifluoperazine", "Diamide", "Thiourea",
"D-Cycloserine", "D-Cycloserine", "Compound 48/80", "Compound 48/80",
"Compound 48/80", "Sodium Dichromate", "Sodium Dichromate", "Sodium Dichromate",
"Manganese (II) Chloride", "Trifluoperazine", "Trifluoperazine",
"Protamine Sulfate", "Manganese (II) Chloride", "Nystatin", "Nystatin",
"Nystatin", "Nystatin", "Diamide", "Diamide", "Thiourea", "Thiourea",
"Dodecyltrimethyl Ammonium Bromide", "Dodecyltrimethyl Ammonium Bromide",
"Dodecyltrimethyl Ammonium Bromide", "Dodecyltrimethyl Ammonium Bromide",
"2,2'-Dipyridyl", "2,2'-Dipyridyl", "2,2'-Dipyridyl", "2,2'-Dipyridyl",
"Protamine Sulfate", "Protamine Sulfate", "Magnesium Chloride",
"Magnesium Chloride", "Guanidine Hydrochloride", "EDTA", "Sodium Selenite",
"Sodium Selenite", "EDTA", "EDTA", "EDTA", "Cetylpyridinium Chloride",
"Cetylpyridinium Chloride", "Cetylpyridinium Chloride", "Cetylpyridinium Chloride",
"Guanidine Hydrochloride", "Manganese (II) Chloride", "Promethazine",
"Promethazine", "Promethazine", "Guanidine Hydrochloride", "Magnesium Chloride",
"Manganese (II) Chloride", "Sodium Selenite", "D-Cycloserine",
"Neomycin", "Magnesium Chloride", "Neomycin", "Neomycin", "Negative Control",
"Sulfate", "Sodium Thiosulfate", "Tetrathionate", "Butane Sulfonic Acid",
"2-Hydroxyethane Sulfonic Acid", "Methane Sulfonic Acid", "Tetramethylene Sulfone",
"Cytidine-3'-Monophosphate", "D-Mannose-1-Phosphate", "D-Mannose-6-Phosphate",
"Cysteamine-S-Phosphate", "Phospho-L-Arginine", "2-Deoxy-D-Glucose-6-Phosphate",
"D-Glucosamine-6-Phosphate", "6-Phospho-Gluconic Acid", "Cytidine-2'-Monophosphate",
"1-Thio-b-D-Glucose", "Cytidine-5'-Monophosphate", "Cytidine-2',3'-Cyclic Monophosphate",
"Cytidine-3',5'-Cyclic Monophosphate", "Glutathione", "D,L-Ethionine",
"L-Methionine", "D-Methionine", "D-Cysteine", "Guanosine-5'-Monophosphate",
"Negative Control", "O-Phospho-D-Tyrosine", "Uridine-5'-Monophosphate",
"Adenosine-3',5'-Cyclic Monophosphate", "L-Cysteic Acid", "L-Methionine Sulfone",
"Taurine", "Cystathionine", "Glycyl-L-Methionine", "L-Djenkolic Acid",
"Hypotaurine", "Cysteamine", "L-Cysteine Sulfinic Acid", "O-Phospho-L-Tyrosine",
"Phosphocreatine", "Phosphorylcholine", "Uridine-2',3'-Cyclic Monophosphate",
"Uridine-3'-Monophosphate", "Uridine-3',5'-Cyclic Monophosphate",
"2-Aminoethyl Phosphonic Acid", "N-Acetyl-D,L-Methionine", "L-Methionine Sulfoxide",
"Guanosine-3'-Monophosphate", "Phosphono Acetic Acid", "Thiophosphate",
"Dithiophosphate", "D,L-a-Glycerol-Phosphate", "b-Glycerol Phosphate",
"Thiourea", "D,L-Lipoamide", "Taurocholic Acid", "p-Amino Benzene Sulfonic Acid",
"Carbamyl Phosphate", "D-2-Phospho-Glyceric Acid", "D-3-Phospho-Glyceric Acid",
"Guanosine-2'-Monophosphate", "Tripolyphosphate", "Triethyl Phosphate",
"Hypophosphite", "Adenosine-2'-Monophosphate", "Guanosine-2',3'-Cyclic Monophosphate",
"Guanosine-3',5'-Cyclic Monophosphate", "Inositol Hexaphosphate",
"Thymidine 3',5'-Cyclic Monophosphate", "Phosphate", "O-Phospho-D-Serine",
"Lanthionine", "N-Acetyl-L-Cysteine", "O-Phospho-L-Serine", "O-Phospho-L-Threonine",
"Uridine-2'-Monophosphate", "Phosphoenol Pyruvate", "Phospho-Glycolic Acid",
"a-D-Glucose-1-Phosphate", "D-Glucose-6-Phosphate", "Pyrophosphate",
"Methylene Diphosphonic Acid", "Adenosine-3'-Monophosphate",
"Adenosine-5'-Monophosphate", "Adenosine-2',3'-Cyclic Monophosphate",
"Trimetaphosphate", "Thymidine-3'-Monophosphate", "O-Phosphoryl-Ethanolamine",
"S-Methyl-L-Cysteine", "L-Cysteinyl-Glycine", "Thiophosphate",
"Thymidine-5'-Monophosphate", "Dithiophosphate", "L-Cysteine",
"3,4-Dimethoxybenzyl Alcohol", "3,4-Dimethoxybenzyl Alcohol",
"3,4-Dimethoxybenzyl Alcohol", "3,4-Dimethoxybenzyl Alcohol",
"Zinc Chloride", "Zinc Chloride", "Zinc Chloride", "Zinc Chloride",
"1,10-Phenanthroline", "Phleomycin", "Phleomycin", "Phleomycin",
"Phleomycin", "Fusidic Acid", "Fusidic Acid", "Fusidic Acid",
"Fusidic Acid", "2-Nitroimidazole", "1,10-Phenanthroline", "1,10-Phenanthroline",
"1,10-Phenanthroline", "Sodium Azide", "Sodium Azide", "Sodium Azide",
"Sodium Azide", "Oleandomycin", "5,7-Dichloro-8-Hydroxy-Quinaldine",
"Procaine", "Alexidine", "Nordihydroguaiaretic Acid", "Cefmetazole",
"Puromycin Dihydrochloride", "Menadione", "Hydroxyurea", "CCCP",
"Menadione", "2-Nitroimidazole", "Hydroxyurea", "Puromycin Dihydrochloride",
"Puromycin Dihydrochloride", "Alexidine", "Alexidine", "Alexidine",
"Nordihydroguaiaretic Acid", "Nordihydroguaiaretic Acid", "Nordihydroguaiaretic Acid",
"Nitrofurazone", "Menadione", "Menadione", "5,7-Dichloro-8-Hydroxy-Quinaldine",
"Nitrofurazone", "D-Cycloserine", "D-Cycloserine", "D-Cycloserine",
"D-Cycloserine", "2-Nitroimidazole", "2-Nitroimidazole", "Hydroxyurea",
"Hydroxyurea", "EDTA", "EDTA", "EDTA", "EDTA", "Guanidine Hydrochloride",
"Guanidine Hydrochloride", "Guanidine Hydrochloride", "Guanidine Hydrochloride",
"5,7-Dichloro-8-Hydroxy-Quinaldine", "5,7-Dichloro-8-Hydroxy-Quinaldine",
"Methyl Viologen", "Methyl Viologen", "Procaine", "Domiphen Bromide",
"CCCP", "CCCP", "Domiphen Bromide", "Domiphen Bromide", "Domiphen Bromide",
"5,7-Dichloro-8-Hydroxyquinoline", "5,7-Dichloro-8-Hydroxyquinoline",
"5,7-Dichloro-8-Hydroxyquinoline", "5,7-Dichloro-8-Hydroxyquinoline",
"Procaine", "Nitrofurazone", "Cefmetazole", "Cefmetazole", "Cefmetazole",
"Procaine", "Methyl Viologen", "Nitrofurazone", "CCCP", "Puromycin Dihydrochloride",
"Oleandomycin", "Methyl Viologen", "Oleandomycin", "Oleandomycin",
"5-Azacytidine", "5-Azacytidine", "5-Azacytidine", "5-Azacytidine",
"Ellagic Acid", "Ellagic Acid", "Ellagic Acid", "Ellagic Acid",
"Emodin", "Puromycin", "Puromycin", "Puromycin", "Puromycin",
"Berberine Chloride", "Berberine Chloride", "Berberine Chloride",
"Berberine Chloride", "Camptothecin", "Emodin", "Emodin", "Emodin",
"1,2-Dimethylhydrazine Hydrochloride", "1,2-Dimethylhydrazine Hydrochloride",
"1,2-Dimethylhydrazine Hydrochloride", "1,2-Dimethylhydrazine Hydrochloride",
"Cycloheximide", "Mycophenolic Acid", "No Chemical", "Carboplatin",
"5-Fluoro-5'-Deoxyuridine", "Thioguanine", "Azaserine", "Phenethyl Caffeate (CAPE)",
"Amygdalin", "p-Fluorophenylalanine", "Phenethyl Caffeate (CAPE)",
"Camptothecin", "Amygdalin", "Azaserine", "Azaserine", "Carboplatin",
"Carboplatin", "Carboplatin", "5-Fluoro-5'-Deoxyuridine", "5-Fluoro-5'-Deoxyuridine",
"5-Fluoro-5'-Deoxyuridine", "Cisplatin", "Phenethyl Caffeate (CAPE)",
"Phenethyl Caffeate (CAPE)", "Mycophenolic Acid", "Cisplatin",
"Acriflavinium Hydrochloride", "Acriflavinium Hydrochloride",
"Acriflavinium Hydrochloride", "Acriflavinium Hydrochloride",
"Camptothecin", "Camptothecin", "Amygdalin", "Amygdalin", "Pentamidine Isethionate",
"Pentamidine Isethionate", "Pentamidine Isethionate", "Pentamidine Isethionate",
"Tamoxifen", "Tamoxifen", "Tamoxifen", "Tamoxifen", "Mycophenolic Acid",
"Mycophenolic Acid", "Zidovudine (AZT)", "Zidovudine (AZT)",
"No Chemical", "Neriifolin", "p-Fluorophenylalanine", "p-Fluorophenylalanine",
"Neriifolin", "Neriifolin", "Neriifolin", "Aminopterin", "Aminopterin",
"Aminopterin", "Aminopterin", "No Chemical", "Cisplatin", "Thioguanine",
"Thioguanine", "Thioguanine", "No Chemical", "Zidovudine (AZT)",
"Cisplatin", "p-Fluorophenylalanine", "Azaserine", "Cycloheximide",
"Zidovudine (AZT)", "Cycloheximide", "Cycloheximide", "Adonitol",
"L-Arabinose", "D-Arabinose", "b-Methyl-D-Xylopyranoside", "3-Hydroxy-2-Butanone",
"Propionic Acid", "Acetic Acid", "Hexanoic Acid", "D-Melezitose",
"D-Tagatose", "L-Sorbose", "L-Rhamnose", "L-Fucose", "D-Mannose",
"a-Methyl-D-Mannoside", "D-Mannitol", "N-Acetyl-b-D-Mannosamine",
"a-Keto-Butyric Acid", "Sucrose", "Palatinose", "D-Turanose",
"Pyruvic Acid", "a-Keto-Glutaric Acid", "Succinamic Acid", "Succinic Acid",
"1,2-Propanediol", "D-Salicin", "Negative Control", "Melibionic Acid",
"D-Lactitol", "b-Gentiobiose", "D,L-a-Glycerol-Phosphate", "m-Tartaric Acid",
"g-Hydroxy-Butyric Acid", "D-Lactic Acid Methyl Ester", "Mono-Methyl Succinate",
"Lithium Acetoacetate", "Butyric Acid", "Glycerol", "Citric Acid",
"D-Melibiose", "D-Galactose", "a-Methyl-D-Galactoside", "Lactulose",
"D-Raffinose", "a-D-Lactose", "Pectin", "L-Malic Acid", "D-Malic Acid",
"b-Methyl-D-Glucoside", "N-Acetyl-Neuraminic Acid", "D-Glucose-6-Phosphate",
"a-D-Glucose-1-Phosphate", "L-Glucose", "D-Glucose", "g-Amino-n-Butyric Acid",
"a-Hydroxy-Butyric Acid", "b-Hydroxy-Butyric Acid", "2,3-Butanediol",
"D-Glucose", "D-Glucose", "3-O-Methyl-D-Glucose", "a-Methyl-D-Glucoside",
"Dextrin", "Glycogen", "Maltitol", "Maltotriose", "D-Sorbitol",
"N-Acetyl-D-Glucosamine", "Adenosine", "Inosine", "Negative Control",
"D-Fucose", "Methyl Pyruvate", "Tricarballylic Acid", "D-Fructose-6-Phosphate",
"D-Fructose", "Stachyose", "D-Glucosaminic Acid", "D-Glucuronic Acid",
"Chondroitin 6-Sulfate", "Mannan", "Negative Control", "Sedoheptulosan",
"D-Maltose", "D-Trehalose", "D-Cellobiose", "a-Cyclodextrin",
"Thymidine", "b-Methyl-D-Galactoside", "D,L-Lactic Acid", "Ethanolamine",
"Xylitol", "Uridine", "myo-Inositol", "m-Erythritol", "Gly-Asp",
"Citric Acid", "myo-Inositol", "D-Threonine", "L-Galactonic Acid-g-Lactone",
"D-Galacturonic Acid", "b-Phenylethylamine", "Ethanolamine",
"D-Glucose", "L-Asparagine", "D-Aspartic Acid", "D-Glucosaminic Acid",
"1,2-Propanediol", "Tween 20", "L-Rhamnose", "D-Fructose", "Acetic Acid",
"m-Hydroxy-Phenylacetic Acid", "D-Maltose", "D-Melibiose", "Thymidine",
"L-Alanine", "L-Alanyl-Glycine", "Acetoacetic Acid", "N-Acetyl-b-D-Mannosamine",
"Mucic Acid", "Sodium Formate", "Negative Control", "L-Glutamine",
"Lactulose", "Dulcitol", "Glyoxylic Acid", "L-Malic Acid", "L-Lyxose",
"L-Serine", "Mono-Methyl Succinate", "Glycyl-L-Proline", "Glucuronamide",
"D-Cellobiose", "Inosine", "m-Tartaric Acid", "a-D-Glucose-1-Phosphate",
"D-Fructose-6-Phosphate", "Sucrose", "a-D-Lactose", "Uridine",
"a-Hydroxy-Butyric Acid", "Methyl Pyruvate", "D-Malic Acid",
"L-Lactic Acid", "a-Hydroxy-Glutaric Acid-g-Lactone", "D-Serine",
"D-Sorbitol", "Glycerol", "L-Fucose", "p-Hydroxy-Phenylacetic Acid",
"Tyramine", "D-Psicose", "Pyruvic Acid", "D-Glucuronic Acid",
"D-Gluconic Acid", "D,L-a-Glycerol-Phosphate", "D-Xylose", "Succinic Acid",
"D-Galactose", "L-Aspartic Acid", "L-Proline", "D-Mannitol",
"L-Glutamic Acid", "2'-Deoxy-Adenosine", "Adenosine", "L-Arabinose",
"Tween 40", "L-Threonine", "Glycyl-L-Glutamic Acid", "a-Keto-Glutaric Acid",
"a-Keto-Butyric Acid", "a-Methyl-D-Galactoside", "D-Glucose-6-Phosphate",
"D-Galactonic Acid-g-Lactone", "D,L-Malic Acid", "D-Ribose",
"N-Acetyl-D-Glucosamine", "b-Methyl-D-Glucoside", "D-Alanine",
"D-Trehalose", "D-Mannose", "D-Saccharic Acid", "Adonitol", "Tween 80",
"Tricarballylic Acid", "Glycolic Acid", "Fumaric Acid", "Maltotriose",
"Bromo-Succinic Acid", "Propionic Acid", "Pectin", "D-Galacturonic Acid",
"L-Galactonic Acid-g-Lactone", "D-Gluconic Acid", "Sodium Formate",
"Aztreonam", "Butyric Acid", "Sodium Bromate", "Inosine", "D-Sorbitol",
"D-Mannitol", "D-Arabitol", "myo-Inositol", "3-O-Methyl-D-Glucose",
"D-Fucose", "L-Fucose", "L-Rhamnose", "a-Hydroxy-Butyric Acid",
"1% Sodium Lactate", "Fusidic Acid", "D-Serine", "Citric Acid",
"a-Keto-Glutaric Acid", "D-Malic Acid", "L-Malic Acid", "Quinic Acid",
"1% NaCl", "Negative Control", "Gelatin", "Troleandomycin", "pH 5",
"Vancomycin", "Potassium Tellurite", "Acetoacetic Acid", "D-Lactic Acid Methyl Ester",
"Bromo-Succinic Acid", "Tween 40", "Propionic Acid", "Tetrazolium Violet",
"Tetrazolium Blue", "Glycyl-L-Proline", "L-Alanine", "L-Arginine",
"Rifamycin SV", "D-Serine", "Minocycline", "L-Histidine", "Nalidixic Acid",
"Lithium Chloride", "N-Acetyl-Neuraminic Acid", "L-Glutamic Acid",
"D-Raffinose", "a-D-Lactose", "D-Melibiose", "b-Methyl-D-Galactoside",
"g-Amino-n-Butyric Acid", "b-Hydroxy-Butyric Acid", "a-Keto-Butyric Acid",
"Acetic Acid", "D-Salicin", "N-Acetyl-D-Glucosamine", "N-Acetyl-b-D-Mannosamine",
"N-Acetyl-D-Galactosamine", "D-Cellobiose", "b-Gentiobiose",
"Sucrose", "D-Turanose", "4% NaCl", "8% NaCl", "Guanidine Hydrochloride",
"Niaproof", "Dextrin", "Glycerol", "L-Lactic Acid", "p-Hydroxy-Phenylacetic Acid",
"D-Glucose-6-Phosphate", "D-Fructose-6-Phosphate", "D-Aspartic Acid",
"D-Glucose", "D-Mannose", "D-Fructose", "D-Galactose", "D-Maltose",
"L-Pyroglutamic Acid", "Stachyose", "Positive Control", "pH 6",
"D-Trehalose", "L-Serine", "L-Aspartic Acid", "Methyl Pyruvate",
"D-Saccharic Acid", "D-Glucuronic Acid", "Lincomycin", "Glucuronamide",
"Mucic Acid", "1% Sodium Lactate", "2% Sodium Lactate", "3% Sodium Lactate",
"4% Sodium Lactate", "40mM Sodium Nitrite", "60mM Sodium Nitrite",
"80mM Sodium Nitrite", "100mM Sodium Nitrite", "6% NaCl + Trimethylamine-N-Oxide",
"3% Potassium Chloride", "4% Potassium Chloride", "5% Potassium Chloride",
"6% Potassium Chloride", "6% NaCl + g-Amino-n-Butyric Acid",
"6% NaCl + Glutathione", "6% NaCl + Glycerol", "6% NaCl + D-Trehalose",
"40mM Sodium Nitrate", "6% NaCl + Trimethylamine", "6% NaCl + Octopine",
"6% NaCl + Trigonelline", "20mM Sodium Benzoate pH 5.2", "50mM Sodium Benzoate pH 5.2",
"100mM Sodium Benzoate pH 5.2", "200mM Sodium Benzoate pH 5.2",
"8% Sodium Lactate", "6% NaCl + Creatine", "1% NaCl", "1% Sodium Formate",
"10% Ethylene Glycol", "10% NaCl", "10% Sodium Lactate", "100mM Ammonium Sulfate pH 8",
"100mM Sodium Nitrate", "100mM Sodium Phosphate pH 7", "10mM Ammonium Sulfate pH 8",
"10mM Sodium Nitrate", "10mM Sodium Nitrite", "11% Sodium Lactate",
"12% Sodium Lactate", "2% Sodium Formate", "3% Sodium Formate",
"4% Sodium Formate", "15% Ethylene Glycol", "5% Ethylene Glycol",
"20% Ethylene Glycol", "2% Urea", "20mM Ammonium Sulfate pH 8",
"50mM Ammonium Sulfate pH 8", "6% NaCl + Phosphorylcholine",
"6% Sodium Formate", "6% NaCl", "6% NaCl + Betaine", "6% NaCl + N-N Dimethyl Glycine",
"6% NaCl + Sarcosine", "20mM Sodium Nitrate", "60mM Sodium Nitrate",
"80mM Sodium Nitrate", "20mM Sodium Nitrite", "6% NaCl + Dimethyl Sulphonyl Propionate",
"6% NaCl + MOPS", "6% NaCl + Ectoine", "6% NaCl + Choline", "5% NaCl",
"5.5% NaCl", "6% NaCl", "6.5% NaCl", "6% NaCl + Creatinine",
"6% NaCl + L-Carnitine", "6% Urea", "7% Urea", "2% NaCl", "2% Sodium Sulfate",
"200mM Sodium Phosphate pH 7", "20mM Sodium Phosphate pH 7",
"3% Sodium Sulfate", "4% Sodium Sulfate", "5% Sodium Sulfate",
"6% NaCl + Potassium Chloride", "6% NaCl + L-Proline", "6% NaCl + N-Acetyl-L-Glutamine",
"6% NaCl + b-Glutamic Acid", "3% NaCl", "3% Urea", "7% NaCl",
"8% NaCl", "9% NaCl", "4% NaCl", "4% Urea", "5% Sodium Formate",
"50mM Sodium Phosphate pH 7", "9% Sodium Lactate", "5% Sodium Lactate",
"5% Urea", "6% Sodium Lactate", "7% Sodium Lactate", "4-Hydroxycoumarin",
"4-Hydroxycoumarin", "4-Hydroxycoumarin", "4-Hydroxycoumarin",
"Troleandomycin", "Troleandomycin", "Troleandomycin", "Troleandomycin",
"Ornidazole", "Proflavine", "Proflavine", "Proflavine", "Proflavine",
"Atropine", "Atropine", "Atropine", "Atropine", "Patulin", "Ornidazole",
"Ornidazole", "Ornidazole", "3,5-Dinitrobenzoic Acid", "3,5-Dinitrobenzoic Acid",
"3,5-Dinitrobenzoic Acid", "3,5-Dinitrobenzoic Acid", "Oxytetracycline",
"Tetrazolium Violet", "Amitriptyline", "Crystal Violet", "18-Crown-6-Ether",
"Benserazide", "Pridinol", "8-Hydroxyquinoline", "Tolylfluanid",
"Captan", "8-Hydroxyquinoline", "Patulin", "Tolylfluanid", "Pridinol",
"Pridinol", "Crystal Violet", "Crystal Violet", "Crystal Violet",
"18-Crown-6-Ether", "18-Crown-6-Ether", "18-Crown-6-Ether", "Dodine",
"8-Hydroxyquinoline", "8-Hydroxyquinoline", "Tetrazolium Violet",
"Dodine", "Orphenadrine", "Orphenadrine", "Orphenadrine", "Orphenadrine",
"Patulin", "Patulin", "Tolylfluanid", "Tolylfluanid", "D,L-Propranolol",
"D,L-Propranolol", "D,L-Propranolol", "D,L-Propranolol", "Apramycin",
"Apramycin", "Apramycin", "Apramycin", "Tetrazolium Violet",
"Tetrazolium Violet", "Hexachlorophene", "Hexachlorophene", "Amitriptyline",
"Ciprofloxacin", "Captan", "Captan", "Ciprofloxacin", "Ciprofloxacin",
"Ciprofloxacin", "Thioridazine", "Thioridazine", "Thioridazine",
"Thioridazine", "Amitriptyline", "Dodine", "Benserazide", "Benserazide",
"Benserazide", "Amitriptyline", "Hexachlorophene", "Dodine",
"Captan", "Pridinol", "Oxytetracycline", "Hexachlorophene", "Oxytetracycline",
"Oxytetracycline", "Sodium Azide", "Sodium Azide", "Sodium Azide",
"Sodium Azide", "Sodium Thiosulfate", "Sodium Thiosulfate", "Sodium Thiosulfate",
"Sodium Thiosulfate", "Poly-L-lysine", "Chromium (III) Chloride",
"Chromium (III) Chloride", "Chromium (III) Chloride", "Chromium (III) Chloride",
"Hydroxylamine", "Hydroxylamine", "Hydroxylamine", "Hydroxylamine",
"Sodium Selenate", "Poly-L-lysine", "Poly-L-lysine", "Poly-L-lysine",
"Sodium Orthovanadate", "Sodium Orthovanadate", "Sodium Orthovanadate",
"Sodium Orthovanadate", "Sodium Caprylate", "Doxycycline", "Benzethonium Chloride",
"Sodium Metaborate", "Cupric Chloride", "Ammonium Sulfate", "Sodium Cyanate",
"2-Deoxy-D-Glucose", "Sodium Cyanide", "Sodium Nitrite", "2-Deoxy-D-Glucose",
"Sodium Selenate", "Sodium Cyanide", "Sodium Cyanate", "Sodium Cyanate",
"Sodium Metaborate", "Sodium Metaborate", "Sodium Metaborate",
"Cupric Chloride", "Cupric Chloride", "Cupric Chloride", "Sodium Metaperiodate",
"2-Deoxy-D-Glucose", "2-Deoxy-D-Glucose", "Doxycycline", "Sodium Metaperiodate",
"Cadmium Chloride", "Cadmium Chloride", "Cadmium Chloride", "Cadmium Chloride",
"Sodium Selenate", "Sodium Selenate", "Sodium Cyanide", "Sodium Cyanide",
"Dequalinium", "Dequalinium", "Dequalinium", "Dequalinium", "Chlorpromazine",
"Chlorpromazine", "Chlorpromazine", "Chlorpromazine", "Doxycycline",
"Doxycycline", "Sodium m-Arsenite", "Sodium m-Arsenite", "Benzethonium Chloride",
"Cobalt (II) Chloride", "Sodium Nitrite", "Sodium Nitrite", "Cobalt (II) Chloride",
"Cobalt (II) Chloride", "Cobalt (II) Chloride", "Glycine", "Glycine",
"Glycine", "Glycine", "Benzethonium Chloride", "Sodium Metaperiodate",
"Ammonium Sulfate", "Ammonium Sulfate", "Ammonium Sulfate", "Benzethonium Chloride",
"Sodium m-Arsenite", "Sodium Metaperiodate", "Sodium Nitrite",
"Sodium Cyanate", "Sodium Caprylate", "Sodium m-Arsenite", "Sodium Caprylate",
"Sodium Caprylate", "D-Lactic Acid Methyl Ester", "Malonic Acid",
"Melibionic Acid", "Oxalic Acid", "Dihydroxy-Acetone", "2,3-Butanediol",
"2,3-Butanedione", "3-Hydroxy-2-Butanone", "b-Methyl-D-Glucuronic Acid",
"D-Raffinose", "D-Salicin", "Sedoheptulosan", "L-Sorbose", "Maltitol",
"a-Methyl-D-Glucoside", "b-Methyl-D-Galactoside", "3-O-Methyl-D-Glucose",
"L-Pyroglutamic Acid", "a-Methyl-D-Mannoside", "b-Methyl-D-Xylopyranoside",
"Palatinose", "Glycine", "L-Histidine", "L-Homoserine", "4-Hydroxy-L-Proline (trans)",
"Sebacic Acid", "m-Erythritol", "Negative Control", "Capric Acid",
"g-Amino-n-Butyric Acid", "Pectin", "Succinamic Acid", "L-Methionine",
"Butylamine (sec)", "N-Acetyl-L-Glutamic Acid", "L-Isoleucine",
"L-Ornithine", "D,L-Octopamine", "D-Tartaric Acid", "L-Tartaric Acid",
"Caproic Acid", "Citraconic Acid", "D-Citramalic Acid", "d-Amino-Valeric Acid",
"N-Acetyl-D-Glucosaminitol", "Butyric Acid", "4-Hydroxy-Benzoic Acid",
"L-Leucine", "L-Lysine", "2-Deoxy-D-Ribose", "2-Hydroxy-Benzoic Acid",
"N-Acetyl-D-Galactosamine", "N-Acetyl-Neuraminic Acid", "b-D-Allose",
"Amygdalin", "L-Phenylalanine", "L-Valine", "D,L-Carnitine",
"Putrescine", "D-Arabinose", "D-Arabitol", "L-Arabitol", "Arbutin",
"g-Cyclodextrin", "Dextrin", "Gelatin", "Glycogen", "D-Fucose",
"3-O-b-D-Galactopyranosyl-D-Arabinose", "Itaconic Acid", "5-Keto-D-Gluconic Acid",
"Chondroitin Sulfate C", "Stachyose", "L-Arginine", "Acetamide",
"D-Tagatose", "Turanose", "Xylitol", "b-Gentiobiose", "L-Glucose",
"D-Lactitol", "D-Melezitose", "a-Cyclodextrin", "b-Hydroxy-Butyric Acid",
"Inulin", "Laminarin", "Mannan", "b-Cyclodextrin", "g-Hydroxy-Butyric Acid",
"D-Glucosamine", "L-Alaninamide", "Sorbic Acid", "Oxalomalic Acid",
"a-Keto-Valeric Acid", "Quinic Acid", "D-Ribono-1,4-Lactone",
"Glycogen", "D-Glucosaminic Acid", "Itaconic Acid", "Glycyl-L-Glutamic Acid",
"a-D-Lactose", "D,L-a-Glycerol-Phosphate", "D-Malic Acid", "Putrescine",
"Tween 40", "Tween 80", "D-Mannitol", "6-Hydroxy-Benzoic Acid",
"L-Serine", "Tween 40", "m-Erythritol", "3-Hydroxy-Benzoic Acid",
"L-Phenylalanine", "D-Malic Acid", "m-Erythritol", "2-Hydroxy-Benzoic Acid",
"L-Phenylalanine", "D-Cellobiose", "a-D-Glucose-1-Phosphate",
"a-Keto-Butyric Acid", "b-Phenylethylamine", "Glycyl-L-Glutamic Acid",
"D-Xylose", "Water", "a-Cyclodextrin", "D-Mannitol", "L-Arginine",
"D-Glucosaminic Acid", "b-Phenylethylamine", "D,L-a-Glycerol-Phosphate",
"a-Keto-Butyric Acid", "D-Cellobiose", "a-D-Lactose", "D-Malic Acid",
"Itaconic Acid", "Glycyl-L-Glutamic Acid", "N-Acetyl-D-Glucosamine",
"g-Hydroxy-Butyric Acid", "L-Threonine", "4-Hydroxy-Benzoic Acid",
"Tween 80", "L-Serine", "g-Hydroxy-Butyric Acid", "a-D-Glucose-1-Phosphate",
"a-Keto-Butyric Acid", "Methyl Pyruvate", "N-Acetyl-D-Glucosamine",
"Methyl Pyruvate", "D-Xylose", "D-Galacturonic Acid", "L-Asparagine",
"D,L-a-Glycerol-Phosphate", "Putrescine", "a-D-Lactose", "Putrescine",
"Methyl Pyruvate", "D-Xylose", "D-Galacturonic Acid", "L-Asparagine",
"Water", "b-Methyl-D-Glucoside", "D-Galactonic Acid-g-Lactone",
"L-Arginine", "D-Galacturonic Acid", "L-Asparagine", "g-Hydroxy-Butyric Acid",
"L-Threonine", "b-Methyl-D-Glucoside", "Tween 80", "b-Phenylethylamine",
"D-Cellobiose", "D-Mannitol", "5-Hydroxy-Benzoic Acid", "L-Serine",
"Tween 40", "m-Erythritol", "4-Hydroxy-Benzoic Acid", "L-Phenylalanine",
"D-Galactonic Acid-g-Lactone", "L-Threonine", "Water", "b-Methyl-D-Glucoside",
"D-Galactonic Acid-g-Lactone", "L-Arginine", "a-Cyclodextrin",
"a-Cyclodextrin", "a-D-Glucose-1-Phosphate", "Glycogen", "Glycogen",
"N-Acetyl-D-Glucosamine", "D-Glucosaminic Acid", "Itaconic Acid",
"Lithium Chloride", "Lithium Chloride", "Lithium Chloride", "Lithium Chloride",
"Phenylarsine Oxide", "Phenylarsine Oxide", "Phenylarsine Oxide",
"Phenylarsine Oxide", "Sulfamonomethoxine", "Oxycarboxin", "Oxycarboxin",
"Oxycarboxin", "Oxycarboxin", "Sulfachloropyridazine", "Sulfachloropyridazine",
"Sulfachloropyridazine", "Sulfachloropyridazine", "Cefsulodin",
"Sulfamonomethoxine", "Sulfamonomethoxine", "Sulfamonomethoxine",
"Cefamandole Nafate", "Cefamandole Nafate", "Cefamandole Nafate",
"Cefamandole Nafate", "D,L-Methionine Hydroxamate", "Ethionamide",
"D-Serine", "Niaproof", "Chlorpromazine", "Thiosalicylate", "Tannic Acid",
"Cefoperazone", "Caffeine", "Chlorambucil", "Cefoperazone", "Cefsulodin",
"Caffeine", "Tannic Acid", "Tannic Acid", "Niaproof", "Niaproof",
"Niaproof", "Chlorpromazine", "Chlorpromazine", "Chlorpromazine",
"Compound 48/80", "Cefoperazone", "Cefoperazone", "Ethionamide",
"Compound 48/80", "2-Hydroxy-Benzoic Acid", "2-Hydroxy-Benzoic Acid",
"2-Hydroxy-Benzoic Acid", "2-Hydroxy-Benzoic Acid", "Cefsulodin",
"Cefsulodin", "Caffeine", "Caffeine", "Hygromycin B", "Hygromycin B",
"Hygromycin B", "Hygromycin B", "b-Chloro-L-Alanine", "b-Chloro-L-Alanine",
"b-Chloro-L-Alanine", "b-Chloro-L-Alanine", "Ethionamide", "Ethionamide",
"Sodium Tungstate", "Sodium Tungstate", "D-Serine", "3-Amino-1,2,4-triazole",
"Chlorambucil", "Chlorambucil", "3-Amino-1,2,4-triazole", "3-Amino-1,2,4-triazole",
"3-Amino-1,2,4-triazole", "4-Aminopyridine", "4-Aminopyridine",
"4-Aminopyridine", "4-Aminopyridine", "D-Serine", "Compound 48/80",
"Thiosalicylate", "Thiosalicylate", "Thiosalicylate", "D-Serine",
"Sodium Tungstate", "Compound 48/80", "Chlorambucil", "Tannic Acid",
"D,L-Methionine Hydroxamate", "Sodium Tungstate", "D,L-Methionine Hydroxamate",
"D,L-Methionine Hydroxamate", "D,L-Malic Acid", "D,L-Malic Acid",
"D,L-Malic Acid", "D,L-Malic Acid", "5-Fluorouracil", "5-Fluorouracil",
"5-Fluorouracil", "5-Fluorouracil", "4-Nitroquinoline N oxide",
"Alexidine", "Alexidine", "Alexidine", "Alexidine", "Amitriptyline",
"Amitriptyline", "Amitriptyline", "Amitriptyline", "Chloroquine",
"4-Nitroquinoline N oxide", "4-Nitroquinoline N oxide", "4-Nitroquinoline N oxide",
"Palladium (II) Chloride", "Palladium (II) Chloride", "Palladium (II) Chloride",
"Palladium (II) Chloride", "D-Tartaric Acid", "Kanamycin", "Hydroxyurea",
"2-Hydroxy-Benzoic Acid", "Floxuridine", "Niaproof", "Fumaric Acid",
"Ibuprofen", "Cinnamic Acid (trans)", "5-Fluorocytosine", "Ibuprofen",
"Chloroquine", "Cinnamic Acid (trans)", "Fumaric Acid", "Fumaric Acid",
"2-Hydroxy-Benzoic Acid", "2-Hydroxy-Benzoic Acid", "2-Hydroxy-Benzoic Acid",
"Floxuridine", "Floxuridine", "Floxuridine", "Succinic Acid",
"Ibuprofen", "Ibuprofen", "Kanamycin", "Succinic Acid", "b-Chloro-L-Alanine",
"b-Chloro-L-Alanine", "b-Chloro-L-Alanine", "b-Chloro-L-Alanine",
"Chloroquine", "Chloroquine", "Cinnamic Acid (trans)", "Cinnamic Acid (trans)",
"Tetrazolium Violet", "Tetrazolium Violet", "Tetrazolium Violet",
"Tetrazolium Violet", "Tobramycin", "Tobramycin", "Tobramycin",
"Tobramycin", "Kanamycin", "Kanamycin", "Clomiphene Citrate",
"Clomiphene Citrate", "Hydroxyurea", "Hygromycin B", "5-Fluorocytosine",
"5-Fluorocytosine", "Hygromycin B", "Hygromycin B", "Hygromycin B",
"4-Aminopyridine", "4-Aminopyridine", "4-Aminopyridine", "4-Aminopyridine",
"Hydroxyurea", "Succinic Acid", "Niaproof", "Niaproof", "Niaproof",
"Hydroxyurea", "Clomiphene Citrate", "Succinic Acid", "5-Fluorocytosine",
"Fumaric Acid", "D-Tartaric Acid", "Clomiphene Citrate", "D-Tartaric Acid",
"D-Tartaric Acid", "Semicarbazide Hydrochloride", "Semicarbazide Hydrochloride",
"Semicarbazide Hydrochloride", "Semicarbazide Hydrochloride",
"Plumbagin", "Plumbagin", "Plumbagin", "Plumbagin", "Pentachlorophenol",
"Sodium m-Arsenite", "Sodium m-Arsenite", "Sodium m-Arsenite",
"Sodium m-Arsenite", "Sulfisoxazole", "Sulfisoxazole", "Sulfisoxazole",
"Sulfisoxazole", "5-Fluoro-5'-Deoxyuridine", "Pentachlorophenol",
"Pentachlorophenol", "Pentachlorophenol", "Guanazole", "Guanazole",
"Guanazole", "Guanazole", "Tinidazole", "Azathioprine", "Ketoprofen",
"Sodium Metasilicate", "Lidocaine", "Thiamphenicol", "Aztreonam",
"Myricetin", "2-Phenylphenol", "Triclosan", "Myricetin", "5-Fluoro-5'-Deoxyuridine",
"2-Phenylphenol", "Aztreonam", "Aztreonam", "Sodium Metasilicate",
"Sodium Metasilicate", "Sodium Metasilicate", "Lidocaine", "Lidocaine",
"Lidocaine", "Sodium Metaperiodate", "Myricetin", "Myricetin",
"Azathioprine", "Sodium Metaperiodate", "Trifluorothymidine",
"Trifluorothymidine", "Trifluorothymidine", "Trifluorothymidine",
"5-Fluoro-5'-Deoxyuridine", "5-Fluoro-5'-Deoxyuridine", "2-Phenylphenol",
"2-Phenylphenol", "Pipemidic Acid", "Pipemidic Acid", "Pipemidic Acid",
"Pipemidic Acid", "Pyrophosphate", "Pyrophosphate", "Pyrophosphate",
"Pyrophosphate", "Azathioprine", "Azathioprine", "Antimony (III) Chloride",
"Antimony (III) Chloride", "Ketoprofen", "Sodium Bromate", "Triclosan",
"Triclosan", "Sodium Bromate", "Sodium Bromate", "Sodium Bromate",
"Poly-L-lysine", "Poly-L-lysine", "Poly-L-lysine", "Poly-L-lysine",
"Ketoprofen", "Sodium Metaperiodate", "Thiamphenicol", "Thiamphenicol",
"Thiamphenicol", "Ketoprofen", "Antimony (III) Chloride", "Sodium Metaperiodate",
"Triclosan", "Aztreonam", "Tinidazole", "Antimony (III) Chloride",
"Tinidazole", "Tinidazole", "Cesium Chloride", "Cesium Chloride",
"Cesium Chloride", "Cesium Chloride", "Tylosin", "Tylosin", "Tylosin",
"Tylosin", "Potassium Chromate", "Cefuroxime", "Cefuroxime",
"Cefuroxime", "Cefuroxime", "Doxycycline", "Doxycycline", "Doxycycline",
"Doxycycline", "Cupric Chloride", "Potassium Chromate", "Potassium Chromate",
"Potassium Chromate", "Manganese (II) Chloride", "Manganese (II) Chloride",
"Manganese (II) Chloride", "Manganese (II) Chloride", "Glycine",
"Oxolinic Acid", "Ampicillin", "Cytarabine", "Rolitetracycline",
"Nickel Chloride", "Thallium (I) Acetate", "Trifluoperazine",
"Moxalactam", "Cobalt (II) Chloride", "Trifluoperazine", "Cupric Chloride",
"Moxalactam", "Thallium (I) Acetate", "Thallium (I) Acetate",
"Cytarabine", "Cytarabine", "Cytarabine", "Rolitetracycline",
"Rolitetracycline", "Rolitetracycline", "Geneticin (G418)", "Trifluoperazine",
"Trifluoperazine", "Oxolinic Acid", "Geneticin (G418)", "Azlocillin",
"Azlocillin", "Azlocillin", "Azlocillin", "Cupric Chloride",
"Cupric Chloride", "Moxalactam", "Moxalactam", "2,2'-Dipyridyl",
"2,2'-Dipyridyl", "2,2'-Dipyridyl", "2,2'-Dipyridyl", "Dequalinium",
"Dequalinium", "Dequalinium", "Dequalinium", "Oxolinic Acid",
"Oxolinic Acid", "Ruthenium Red", "Ruthenium Red", "Ampicillin",
"5-Fluorouracil", "Cobalt (II) Chloride", "Cobalt (II) Chloride",
"5-Fluorouracil", "5-Fluorouracil", "5-Fluorouracil", "6-Mercaptopurine",
"6-Mercaptopurine", "6-Mercaptopurine", "6-Mercaptopurine", "Ampicillin",
"Geneticin (G418)", "Nickel Chloride", "Nickel Chloride", "Nickel Chloride",
"Ampicillin", "Ruthenium Red", "Geneticin (G418)", "Cobalt (II) Chloride",
"Thallium (I) Acetate", "Glycine", "Ruthenium Red", "Glycine",
"Glycine", "Bromo-Succinic Acid", "Succinamic Acid", "Glucuronamide",
"L-Alaninamide", "Glycerol", "D,L-a-Glycerol-Phosphate", "a-D-Glucose-1-Phosphate",
"D-Glucose-6-Phosphate", "Turanose", "Acetic Acid", "Cis-Aconitic Acid",
"Citric Acid", "Sodium Formate", "L-Rhamnose", "D-Sorbitol",
"Sucrose", "D-Trehalose", "Uridine", "Xylitol", "Methyl Pyruvate",
"Mono-Methyl Succinate", "L-Phenylalanine", "L-Proline", "L-Pyroglutamic Acid",
"D-Serine", "L-Asparagine", "D-Maltose", "Water", "p-Hydroxy-Phenylacetic Acid",
"a-Hydroxy-Butyric Acid", "D-Cellobiose", "L-Glutamic Acid",
"g-Amino-n-Butyric Acid", "Putrescine", "L-Leucine", "L-Serine",
"Urocanic Acid", "Ethanolamine", "Gly-Asp", "Glycyl-L-Glutamic Acid",
"Itaconic Acid", "a-Keto-Butyric Acid", "a-Keto-Glutaric Acid",
"b-Hydroxy-Butyric Acid", "D-Glucuronic Acid", "g-Hydroxy-Butyric Acid",
"Malonic Acid", "L-Threonine", "D,L-Carnitine", "Lactulose",
"D,L-Lactic Acid", "m-Erythritol", "D-Fructose", "L-Fucose",
"D-Galactose", "Inosine", "Thymidine", "b-Phenylethylamine",
"2,3-Butanediol", "b-Gentiobiose", "D-Glucose", "myo-Inositol",
"a-D-Lactose", "Tween 40", "Tween 80", "N-Acetyl-D-Galactosamine",
"N-Acetyl-D-Glucosamine", "D-Mannitol", "D-Mannose", "Sebacic Acid",
"Succinic Acid", "a-Cyclodextrin", "D-Galactonic Acid-g-Lactone",
"L-Ornithine", "L-Histidine", "D-Gluconic Acid", "D-Galacturonic Acid",
"D-Glucosaminic Acid", "D-Melibiose", "b-Methyl-D-Glucoside",
"D-Psicose", "D-Raffinose", "Dextrin", "Propionic Acid", "Adonitol",
"L-Arabinose", "D-Arabitol", "Glycogen", "Quinic Acid", "a-Keto-Valeric Acid",
"Hydroxy-L-Proline", "L-Aspartic Acid", "D-Alanine", "D-Saccharic Acid",
"L-Alanine", "L-Alanyl-Glycine", "D,L-Lactamide", "D-Lactic Acid Methyl Ester",
"L-Lactic Acid", "D-Malic Acid", "D-Fructose-6-Phosphate", "a-D-Glucose-1-Phosphate",
"D-Glucose-6-Phosphate", "D,L-a-Glycerol-Phosphate", "a-Methyl-D-Galactoside",
"b-Methyl-D-Glucoside", "a-Methyl-D-Mannoside", "Palatinose",
"D-Psicose", "D-Mannitol", "D-Mannose", "D-Melezitose", "D-Melibiose",
"Inosine", "b-Methyl-D-Galactoside", "3-O-Methyl-D-Glucose",
"a-Methyl-D-Glucoside", "L-Asparagine", "L-Glutamic Acid", "Glycyl-L-Glutamic Acid",
"L-Pyroglutamic Acid", "Propionic Acid", "D-Gluconic Acid", "Water",
"D-Tagatose", "D-Sorbitol", "Amygdalin", "Succinamic Acid", "Glycerol",
"Adenosine-5'-Monophosphate", "L-Alanine", "L-Serine", "Adenosine",
"Thymidine-5'-Monophosphate", "Succinic Acid", "N-Acetyl-L-Glutamic Acid",
"D-Trehalose", "Turanose", "Xylitol", "Stachyose", "Sedoheptulosan",
"Sucrose", "a-Hydroxy-Butyric Acid", "Putrescine", "2,3-Butanediol",
"b-Gentiobiose", "Acetic Acid", "L-Arabinose", "D-Arabitol",
"Arbutin", "D-Cellobiose", "2'-Deoxy-Adenosine", "Thymidine",
"Uridine", "Uridine-5'-Monophosphate", "D-Fructose", "L-Fucose",
"D-Galactose", "D-Galacturonic Acid", "Glycogen", "Inulin", "Mannan",
"Tween 40", "D-Glucose", "myo-Inositol", "a-Keto-Glutaric Acid",
"a-Keto-Valeric Acid", "a-Cyclodextrin", "D-Raffinose", "L-Alanyl-Glycine",
"L-Alaninamide", "L-Rhamnose", "D-Ribose", "D-Salicin", "a-D-Lactose",
"Lactulose", "D-Maltose", "Maltotriose", "b-Cyclodextrin", "b-Hydroxy-Butyric Acid",
"Tween 80", "N-Acetyl-D-Glucosamine", "N-Acetyl-b-D-Mannosamine",
"Dextrin", "g-Hydroxy-Butyric Acid", "D-Xylose", "D-Alanine",
"Pyruvic Acid", "L-Malic Acid", "p-Hydroxy-Phenylacetic Acid",
"Methyl Pyruvate", "Mono-Methyl Succinate", "Tobramycin", "Tobramycin",
"Tobramycin", "Tobramycin", "Dodecyltrimethyl Ammonium Bromide",
"Dodecyltrimethyl Ammonium Bromide", "Dodecyltrimethyl Ammonium Bromide",
"Dodecyltrimethyl Ammonium Bromide", "D,L-Serine Hydroxamate",
"Sisomicin", "Sisomicin", "Sisomicin", "Sisomicin", "Vancomycin",
"Vancomycin", "Vancomycin", "Vancomycin", "Spiramycin", "D,L-Serine Hydroxamate",
"D,L-Serine Hydroxamate", "D,L-Serine Hydroxamate", "Sulfamethoxazole",
"Sulfamethoxazole", "Sulfamethoxazole", "Sulfamethoxazole", "Sulfathiazole",
"Polymyxin B", "Penicillin G", "2,4-Diamino-6,7-Diisopropylpteridine",
"Novobiocin", "Carbenicillin", "5-Fluoroorotic Acid", "L-Aspartic-b-Hydroxamate",
"Rifampicin", "Spectinomycin", "L-Aspartic-b-Hydroxamate", "Spiramycin",
"Rifampicin", "5-Fluoroorotic Acid", "5-Fluoroorotic Acid", "2,4-Diamino-6,7-Diisopropylpteridine",
"2,4-Diamino-6,7-Diisopropylpteridine", "2,4-Diamino-6,7-Diisopropylpteridine",
"Novobiocin", "Novobiocin", "Novobiocin", "Sulfadiazine", "L-Aspartic-b-Hydroxamate",
"L-Aspartic-b-Hydroxamate", "Polymyxin B", "Sulfadiazine", "Oxacillin",
"Oxacillin", "Oxacillin", "Oxacillin", "Spiramycin", "Spiramycin",
"Rifampicin", "Rifampicin", "Penimepicycline", "Penimepicycline",
"Penimepicycline", "Penimepicycline", "Tetracycline", "Tetracycline",
"Tetracycline", "Tetracycline", "Polymyxin B", "Polymyxin B",
"Benzethonium Chloride", "Benzethonium Chloride", "Penicillin G",
"Sulfamethazine", "Spectinomycin", "Spectinomycin", "Sulfamethazine",
"Sulfamethazine", "Sulfamethazine", "Paromomycin", "Paromomycin",
"Paromomycin", "Paromomycin", "Penicillin G", "Sulfadiazine",
"Carbenicillin", "Carbenicillin", "Carbenicillin", "Penicillin G",
"Benzethonium Chloride", "Sulfadiazine", "Spectinomycin", "5-Fluoroorotic Acid",
"Sulfathiazole", "Benzethonium Chloride", "Sulfathiazole", "Sulfathiazole",
"Phenethicillin", "Phenethicillin", "Phenethicillin", "Phenethicillin",
"Polymyxin B", "Polymyxin B", "Polymyxin B", "Polymyxin B", "Cinnamic Acid (trans)",
"Disulphiram", "Disulphiram", "Disulphiram", "Disulphiram", "Umbelliferone",
"Umbelliferone", "Umbelliferone", "Umbelliferone", "Hexaminecobalt (III) Chloride",
"Cinnamic Acid (trans)", "Cinnamic Acid (trans)", "Cinnamic Acid (trans)",
"Dihydrostreptomycin", "Dihydrostreptomycin", "Dihydrostreptomycin",
"Dihydrostreptomycin", "Blasticidin S", "2,4-Dinitrophenol",
"Josamycin", "FCCP", "Phenyl-Methyl-Sulfonyl Fluoride", "Coumarin",
"Sodium Caprylate", "Hydroxylamine", "a-Thioglycerol", "Lauryl Sulfobetaine",
"Hydroxylamine", "Hexaminecobalt (III) Chloride", "a-Thioglycerol",
"Sodium Caprylate", "Sodium Caprylate", "FCCP", "FCCP", "FCCP",
"Phenyl-Methyl-Sulfonyl Fluoride", "Phenyl-Methyl-Sulfonyl Fluoride",
"Phenyl-Methyl-Sulfonyl Fluoride", "D,L-a-Lipoic Acid", "Hydroxylamine",
"Hydroxylamine", "2,4-Dinitrophenol", "D,L-a-Lipoic Acid", "Methyltrioctylammonium Chloride",
"Methyltrioctylammonium Chloride", "Methyltrioctylammonium Chloride",
"Methyltrioctylammonium Chloride", "Hexaminecobalt (III) Chloride",
"Hexaminecobalt (III) Chloride", "a-Thioglycerol", "a-Thioglycerol",
"Harmane", "Harmane", "Harmane", "Harmane", "Gallic Acid", "Gallic Acid",
"Gallic Acid", "Gallic Acid", "2,4-Dinitrophenol", "2,4-Dinitrophenol",
"Lawsone", "Lawsone", "Josamycin", "Iodonitro Tetrazolium Violet",
"Lauryl Sulfobetaine", "Lauryl Sulfobetaine", "Iodonitro Tetrazolium Violet",
"Iodonitro Tetrazolium Violet", "Iodonitro Tetrazolium Violet",
"Chlorhexidine", "Chlorhexidine", "Chlorhexidine", "Chlorhexidine",
"Josamycin", "D,L-a-Lipoic Acid", "Coumarin", "Coumarin", "Coumarin",
"Josamycin", "Lawsone", "D,L-a-Lipoic Acid", "Lauryl Sulfobetaine",
"Sodium Caprylate", "Blasticidin S", "Lawsone", "Blasticidin S",
"Blasticidin S", "Azaserine", "Azaserine", "Azaserine", "Azaserine",
"Myclobutanil", "Myclobutanil", "Myclobutanil", "Myclobutanil",
"D,L-Serine Hydroxamate", "Polymyxin B", "Polymyxin B", "Polymyxin B",
"Polymyxin B", "Miltefosine", "Miltefosine", "Miltefosine", "Miltefosine",
"Bleomycin", "D,L-Serine Hydroxamate", "D,L-Serine Hydroxamate",
"D,L-Serine Hydroxamate", "Cycloheximide", "Cycloheximide", "Cycloheximide",
"Cycloheximide", "Lithium Chloride", "Triclosan", "L-Glutamic Acid g-Hydroxamate",
"CCCP", "Sodium Arsenate", "Caffeine", "FCCP", "Thallium (I) Acetate",
"Paromomycin", "Benzamidine hydrochloride hydrate", "Thallium (I) Acetate",
"Bleomycin", "Paromomycin", "FCCP", "FCCP", "CCCP", "CCCP", "CCCP",
"Sodium Arsenate", "Sodium Arsenate", "Sodium Arsenate", "BAPTA",
"Thallium (I) Acetate", "Thallium (I) Acetate", "Triclosan",
"BAPTA", "L-Arginine Hydroxamate", "L-Arginine Hydroxamate",
"L-Arginine Hydroxamate", "L-Arginine Hydroxamate", "Bleomycin",
"Bleomycin", "Paromomycin", "Paromomycin", "Glycine Hydroxamate",
"Glycine Hydroxamate", "Glycine Hydroxamate", "Glycine Hydroxamate",
"Sodium Metavanadate", "Sodium Metavanadate", "Sodium Metavanadate",
"Sodium Metavanadate", "Triclosan", "Triclosan", "D-Serine",
"D-Serine", "L-Glutamic Acid g-Hydroxamate", "Urea hydrogen peroxide",
"Benzamidine hydrochloride hydrate", "Benzamidine hydrochloride hydrate",
"Urea hydrogen peroxide", "Urea hydrogen peroxide", "Urea hydrogen peroxide",
"3-Amino-1,2,4-triazole", "3-Amino-1,2,4-triazole", "3-Amino-1,2,4-triazole",
"3-Amino-1,2,4-triazole", "L-Glutamic Acid g-Hydroxamate", "BAPTA",
"Caffeine", "Caffeine", "Caffeine", "L-Glutamic Acid g-Hydroxamate",
"D-Serine", "BAPTA", "Benzamidine hydrochloride hydrate", "FCCP",
"Lithium Chloride", "D-Serine", "Lithium Chloride", "Lithium Chloride",
"Dexamethasone", "Dexamethasone", "Dexamethasone", "Dexamethasone",
"Aldosterone", "Aldosterone", "Aldosterone", "Aldosterone", "Norepinephrine",
"L-Leucine", "L-Leucine", "L-Leucine", "L-Leucine", "Epinephrine",
"Epinephrine", "Norepinephrine", "Norepinephrine", "4,5-a-Dihydrotestosterone",
"Norepinephrine", "Norepinephrine", "Norepinephrine", "Progesterone",
"Progesterone", "b-Estradiol", "b-Estradiol", "Hydrocortisone",
"Caffeine", "Negative Control", "Triiodothyronine", "Creatine",
"Dibutyryl-cAMP", "Hydrocortisone", "b-Estradiol", "4,5-a-Dihydrotestosterone",
"Progesterone", "b-Estradiol", "4,5-a-Dihydrotestosterone", "Aldosterone",
"Hydrocortisone", "Hydrocortisone", "Triiodothyronine", "Triiodothyronine",
"Triiodothyronine", "Creatine", "Creatine", "Creatine", "Thyroxine",
"b-Estradiol", "b-Estradiol", "Caffeine", "Triiodothyronine",
"3-Isobutyl-1-Methylxanthine", "3-Isobutyl-1-Methylxanthine",
"3-Isobutyl-1-Methylxanthine", "3-Isobutyl-1-Methylxanthine",
"4,5-a-Dihydrotestosterone", "4,5-a-Dihydrotestosterone", "4,5-a-Dihydrotestosterone",
"Aldosterone", "3-Isobutyl-1-Methylxanthine", "3-Isobutyl-1-Methylxanthine",
"Caffeine", "Caffeine", "Negative Control", "Negative Control",
"Dibutyryl-cAMP", "Dibutyryl-cAMP", "Caffeine", "Caffeine", "Thyroxine",
"Thyroxine", "Negative Control", "L-Leucine", "Progesterone",
"Progesterone", "L-Leucine", "Creatine", "Creatine", "Epinephrine",
"Epinephrine", "Epinephrine", "Epinephrine", "Negative Control",
"Thyroxine", "Dibutyryl-cAMP", "Dibutyryl-cAMP", "Dibutyryl-cAMP",
"Negative Control", "Thyroxine", "Triiodothyronine", "Progesterone",
"Hydrocortisone", "Dexamethasone", "Thyroxine", "Dexamethasone",
"Hydrocortisone", "Cyclophosphamide Hydrate", "Cyclophosphamide Hydrate",
"Cyclophosphamide Hydrate", "Cyclophosphamide Hydrate", "Streptozosin",
"Streptozosin", "Streptozosin", "Streptozosin", "Dactinomycin",
"Methylmethane Sulfonate", "Methylmethane Sulfonate", "Methylmethane Sulfonate",
"Methylmethane Sulfonate", "Sanguinarine Sulfate", "Sanguinarine Sulfate",
"Sanguinarine Sulfate", "Sanguinarine Sulfate", "Mercaptopurine",
"Dactinomycin", "Dactinomycin", "Dactinomycin", "Hydroxyurea",
"Hydroxyurea", "Hydroxyurea", "Hydroxyurea", "Diethylcarbamazine Citrate",
"Celastrol", "No Chemical", "Aclarubicin", "Busulfan", "Rotenone",
"Emetine Hydrochloride", "Mechlorethamine", "Quinacrine Hydrochloride",
"5-Fluorouracil", "Mechlorethamine", "Mercaptopurine", "Quinacrine Hydrochloride",
"Emetine Hydrochloride", "Emetine Hydrochloride", "Aclarubicin",
"Aclarubicin", "Aclarubicin", "Busulfan", "Busulfan", "Busulfan",
"Chloramphenicol", "Mechlorethamine", "Mechlorethamine", "Celastrol",
"Chloramphenicol", "Aklavine Hydrochloride", "Aklavine Hydrochloride",
"Aklavine Hydrochloride", "Aklavine Hydrochloride", "Mercaptopurine",
"Mercaptopurine", "Quinacrine Hydrochloride", "Quinacrine Hydrochloride",
"Deguelin (-)", "Deguelin (-)", "Deguelin (-)", "Deguelin (-)",
"Solasodine", "Solasodine", "Solasodine", "Solasodine", "Celastrol",
"Celastrol", "Chloroquine", "Chloroquine", "No Chemical", "Azathioprine",
"5-Fluorouracil", "5-Fluorouracil", "Azathioprine", "Azathioprine",
"Azathioprine", "Juglone", "Juglone", "Juglone", "Juglone", "No Chemical",
"Chloramphenicol", "Rotenone", "Rotenone", "Rotenone", "No Chemical",
"Chloroquine", "Chloramphenicol", "5-Fluorouracil", "Emetine Hydrochloride",
"Diethylcarbamazine Citrate", "Chloroquine", "Diethylcarbamazine Citrate",
"Diethylcarbamazine Citrate", "Aminolevulinic Acid Hydrochloride",
"Aminolevulinic Acid Hydrochloride", "Aminolevulinic Acid Hydrochloride",
"Aminolevulinic Acid Hydrochloride", "Rifaximin", "Rifaximin",
"Rifaximin", "Rifaximin", "Pipobroman", "Etanidazole", "Etanidazole",
"Etanidazole", "Etanidazole", "Thiodiglycol", "Thiodiglycol",
"Thiodiglycol", "Thiodiglycol", "Carmofur", "Pipobroman", "Pipobroman",
"Pipobroman", "Dibenzoylmethane", "Dibenzoylmethane", "Dibenzoylmethane",
"Dibenzoylmethane", "Picropodophyllotoxin", "Urethane", "No Chemical",
"Formestane", "Gossypol", "Altretamine", "b-Peltatin", "6-Aminonicotinamide",
"Indole-3-Carbinol", "Perillyl Alcohol", "6-Aminonicotinamide",
"Carmofur", "Indole-3-Carbinol", "b-Peltatin", "b-Peltatin",
"Formestane", "Formestane", "Formestane", "Gossypol", "Gossypol",
"Gossypol", "Ancitabine Hydrochloride", "6-Aminonicotinamide",
"6-Aminonicotinamide", "Urethane", "Ancitabine Hydrochloride",
"Carmustine", "Carmustine", "Carmustine", "Carmustine", "Carmofur",
"Carmofur", "Indole-3-Carbinol", "Indole-3-Carbinol", "Mitoxantrone Hydrochloride",
"Mitoxantrone Hydrochloride", "Mitoxantrone Hydrochloride", "Mitoxantrone Hydrochloride",
"Monocrotaline", "Monocrotaline", "Monocrotaline", "Monocrotaline",
"Urethane", "Urethane", "Nimustine", "Nimustine", "No Chemical",
"Semustine", "Perillyl Alcohol", "Perillyl Alcohol", "Semustine",
"Semustine", "Semustine", "Thiotepa", "Thiotepa", "Thiotepa",
"Thiotepa", "No Chemical", "Ancitabine Hydrochloride", "Altretamine",
"Altretamine", "Altretamine", "No Chemical", "Nimustine", "Ancitabine Hydrochloride",
"Perillyl Alcohol", "b-Peltatin", "Picropodophyllotoxin", "Nimustine",
"Picropodophyllotoxin", "Picropodophyllotoxin", "a-Keto-Glutaric Acid",
"a-Keto-Glutaric Acid", "a-Keto-Glutaric Acid", "a-Keto-Glutaric Acid",
"Pyruvic Acid", "Pyruvic Acid", "Pyruvic Acid", "Pyruvic Acid",
"D-Galactose", "a-D-Glucose-1-Phosphate", "a-D-Glucose-1-Phosphate",
"a-D-Glucose-1-Phosphate", "a-D-Glucose-1-Phosphate", "D-Galactose",
"D-Galactose", "D-Galactose", "D-Galactose", "Pyruvic Acid",
"D-Galactose", "D-Galactose", "D-Galactose", "b-Hydroxy-Butyric Acid",
"b-Hydroxy-Butyric Acid", "b-Hydroxy-Butyric Acid", "b-Hydroxy-Butyric Acid",
"a-Keto-Glutaric Acid", "Inosine", "D-Glucose", "Xylitol", "a-D-Glucose-1-Phosphate",
"D-Glucose", "a-Keto-Glutaric Acid", "b-Hydroxy-Butyric Acid",
"Pyruvic Acid", "b-Hydroxy-Butyric Acid", "b-Hydroxy-Butyric Acid",
"Pyruvic Acid", "Pyruvic Acid", "a-Keto-Glutaric Acid", "a-Keto-Glutaric Acid",
"Xylitol", "Xylitol", "Xylitol", "a-D-Glucose-1-Phosphate", "a-D-Glucose-1-Phosphate",
"a-D-Glucose-1-Phosphate", "Xylitol", "b-Hydroxy-Butyric Acid",
"b-Hydroxy-Butyric Acid", "Inosine", "Xylitol", "Inosine", "Inosine",
"Inosine", "Inosine", "Pyruvic Acid", "Pyruvic Acid", "Pyruvic Acid",
"Pyruvic Acid", "Inosine", "Inosine", "Inosine", "Inosine", "D-Glucose",
"D-Glucose", "D-Glucose", "D-Glucose", "Inosine", "Inosine",
"Xylitol", "Xylitol", "D-Glucose", "a-D-Glucose-1-Phosphate",
"b-Hydroxy-Butyric Acid", "b-Hydroxy-Butyric Acid", "a-D-Glucose-1-Phosphate",
"a-D-Glucose-1-Phosphate", "a-D-Glucose-1-Phosphate", "D-Galactose",
"D-Galactose", "D-Galactose", "D-Galactose", "D-Glucose", "Xylitol",
"D-Glucose", "D-Glucose", "D-Glucose", "D-Glucose", "Xylitol",
"Xylitol", "b-Hydroxy-Butyric Acid", "a-Keto-Glutaric Acid",
"a-Keto-Glutaric Acid", "Xylitol", "a-Keto-Glutaric Acid", "a-Keto-Glutaric Acid",
"N-Acetyl-b-D-Mannosamine", "Adenine", "Adenosine", "Cytidine",
"Gly-Gln", "Gly-Glu", "Gly-Met", "Met-Ala", "D-Valine", "N-Acetyl-L-Glutamic Acid",
"N-Phthaloyl-L-Glutamic Acid", "L-Pyroglutamic Acid", "Hydroxylamine",
"D-Aspartic Acid", "D-Glutamic Acid", "D-Lysine", "D-Serine",
"Ala-Glu", "L-Citrulline", "L-Homoserine", "L-Ornithine", "Allantoin",
"Parabanic Acid", "D,L-a-Amino-Butyric Acid", "g-Amino-n-Butyric Acid",
"Thymine", "L-Serine", "Negative Control", "Histamine", "Ethylenediamine",
"L-Glutamic Acid", "Uracil", "L-Norvaline", "Ala-Leu", "Uric Acid",
"e-Amino-N-Caproic Acid", "Ala-Asp", "Ala-Thr", "Uridine", "Inosine",
"b-Phenylethylamine", "Tyramine", "Acetamide", "Putrescine",
"Ethanolamine", "Agmatine", "D,L-Lactamide", "D,L-a-Amino-Caprylic Acid",
"d-Amino-Valeric Acid", "L-Proline", "Glucuronamide", "L-Glutamine",
"Glycine", "L-Histidine", "L-Isoleucine", "Ala-Gln", "Ala-Gly",
"Ala-His", "Gly-Asn", "L-Leucine", "L-Lysine", "L-Methionine",
"L-Phenylalanine", "Urea", "Biuret", "L-Alanine", "L-Arginine",
"L-Threonine", "L-Tryptophan", "N-Acetyl-D-Glucosamine", "N-Acetyl-D-Galactosamine",
"Ammonia", "Methylamine", "Alloxan", "Xanthine", "N-Amylamine",
"N-Butylamine", "Ethylamine", "L-Tyrosine", "L-Valine", "D-Alanine",
"D-Asparagine", "Sodium Nitrite", "D-Glucosamine", "L-Asparagine",
"L-Aspartic Acid", "L-Cysteine", "Sodium Nitrate", "D-Galactosamine",
"Formamide", "Xanthosine", "Thymidine", "Cytosine", "D-Mannosamine",
"Guanine", "Guanosine", "Thyrotropic Hormone (TSH)", "Thyrotropic Hormone (TSH)",
"Thyrotropic Hormone (TSH)", "Thyrotropic Hormone (TSH)", "Gly-His-Lys Acetate Salt",
"Gly-His-Lys Acetate Salt", "Gly-His-Lys Acetate Salt", "Gly-His-Lys Acetate Salt",
"Calcitriol (1a,25-dihydroxyvitamin D3)", "Luteinizing Hormone (LH)",
"Luteinizing Hormone (LH)", "Luteinizing Hormone (LH)", "Luteinizing Hormone (LH)",
"Calcitonin", "Calcitonin", "Calcitriol (1a,25-dihydroxyvitamin D3)",
"Calcitriol (1a,25-dihydroxyvitamin D3)", "Adenosine", "Calcitriol (1a,25-dihydroxyvitamin D3)",
"Calcitriol (1a,25-dihydroxyvitamin D3)", "Calcitriol (1a,25-dihydroxyvitamin D3)",
"IFN-g", "IFN-g", "TNF-a", "TNF-a", "Thyrotropin Releasing Hormone Acetate Salt (TRH)",
"Prolactin", "Negative Control", "Chorionic Gonadotropin Human (HCG)",
"Luteinizing Hormone Releasing Hormone (LH-RH)", "Arginine-Vasopressin",
"Thyrotropin Releasing Hormone Acetate Salt (TRH)", "TNF-a",
"Adenosine", "IFN-g", "TNF-a", "Adenosine", "Gly-His-Lys Acetate Salt",
"Thyrotropin Releasing Hormone Acetate Salt (TRH)", "Thyrotropin Releasing Hormone Acetate Salt (TRH)",
"Chorionic Gonadotropin Human (HCG)", "Chorionic Gonadotropin Human (HCG)",
"Chorionic Gonadotropin Human (HCG)", "Luteinizing Hormone Releasing Hormone (LH-RH)",
"Luteinizing Hormone Releasing Hormone (LH-RH)", "Luteinizing Hormone Releasing Hormone (LH-RH)",
"Adrenocorticotropic Hormone Human (ACTH)", "TNF-a", "TNF-a",
"Prolactin", "Chorionic Gonadotropin Human (HCG)", "Parathyroid Hormone",
"Parathyroid Hormone", "Parathyroid Hormone", "Parathyroid Hormone",
"Adenosine", "Adenosine", "Adenosine", "Gly-His-Lys Acetate Salt",
"Parathyroid Hormone", "Parathyroid Hormone", "Prolactin", "Prolactin",
"Negative Control", "Negative Control", "Arginine-Vasopressin",
"Arginine-Vasopressin", "Prolactin", "Prolactin", "Adrenocorticotropic Hormone Human (ACTH)",
"Adrenocorticotropic Hormone Human (ACTH)", "Negative Control",
"Luteinizing Hormone (LH)", "IFN-g", "IFN-g", "Luteinizing Hormone (LH)",
"Luteinizing Hormone Releasing Hormone (LH-RH)", "Luteinizing Hormone Releasing Hormone (LH-RH)",
"Calcitonin", "Calcitonin", "Calcitonin", "Calcitonin", "Negative Control",
"Adrenocorticotropic Hormone Human (ACTH)", "Arginine-Vasopressin",
"Arginine-Vasopressin", "Arginine-Vasopressin", "Negative Control",
"Adrenocorticotropic Hormone Human (ACTH)", "Chorionic Gonadotropin Human (HCG)",
"IFN-g", "Thyrotropin Releasing Hormone Acetate Salt (TRH)",
"Thyrotropic Hormone (TSH)", "Adrenocorticotropic Hormone Human (ACTH)",
"Thyrotropic Hormone (TSH)", "Thyrotropin Releasing Hormone Acetate Salt (TRH)",
"Arg-Leu", "Arg-Lys", "Arg-Met", "Arg-Phe", "Gly-Arg", "Gly-Asn",
"Gly-Asp", "D-Glucose", "L-Tryptophan", "Ala-Arg", "Ala-Asn",
"Ala-Asp", "Ala-Glu", "L-Serine", "D-Serine", "L-Threonine",
"D-Threonine", "Glu-Tyr", "L-Tyrosine", "L-Valine", "Ala-Ala",
"Asp-Lys", "Asp-Phe", "Asp-Trp", "Asp-Val", "Arg-Val", "L-Isoleucine",
"Negative Control", "Ala-Pro", "Ala-Lys", "L-Asparagine", "Asn-Val",
"Glu-Gly", "Gln-Gln", "Asp-Gly", "Glu-Ala", "Glu-Ser", "Gln-Gly",
"Asp-Ala", "Asp-Asp", "Ala-Ser", "Ala-Thr", "Ala-Trp", "Ala-Met",
"Ala-Leu", "Ala-Phe", "Arg-Ala", "Glu-Asp", "Glu-Glu", "Hydroxy-L-Proline",
"Ala-Val", "L-Aspartic Acid", "D-Aspartic Acid", "L-Glutamic Acid",
"D-Glutamic Acid", "Glu-Trp", "Glu-Val", "Gln-Glu", "Gly-Ala",
"L-Glutamine", "Glycine", "L-Histidine", "L-Homoserine", "Tween 40",
"Tween 80", "Gelatin", "L-Alaninamide", "L-Leucine", "L-Lysine",
"Arg-Glu", "Arg-Ile", "Negative Control", "Ala-Gln", "Asp-Leu",
"Asp-Glu", "Ala-Gly", "Ala-His", "Ala-Ile", "L-Methionine", "L-Ornithine",
"L-Phenylalanine", "L-Proline", "Negative Control", "Arg-Arg",
"L-Alanine", "D-Alanine", "L-Arginine", "Tween 20", "Arg-Asp",
"Ala-Tyr", "Asp-Gln", "Asn-Glu", "Arg-Ser", "Arg-Gln", "Arg-Trp",
"Arg-Tyr", "Gly-Thr", "Gly-Trp", "Gly-Tyr", "Gly-Val", "Leu-Ile",
"Leu-Leu", "Leu-Met", "Leu-Phe", "Asp-Asp", "Asp-Phe", "Asp-Trp",
"Asp-Val", "Cys-Gly", "Arg-Tyr", "Arg-Val", "Asn-Glu", "Asn-Val",
"Ile-Val", "Asp-Glu", "Asp-Leu", "Asp-Lys", "Ile-Gln", "Ile-Gly",
"Ile-His", "Ile-Ile", "His-Lys", "Arg-Ile", "Negative Control",
"Glu-Val", "Glu-Ser", "Ala-Pro", "His-Pro", "Ile-Ser", "Leu-Asp",
"Ile-Ala", "Ile-Met", "Ile-Trp", "Leu-Glu", "His-Ser", "His-Trp",
"Gly-Ala", "Gly-Arg", "Gly-Cys", "Glu-Trp", "Glu-Gly", "Glu-Tyr",
"Gly-Leu", "Ile-Phe", "Ile-Pro", "Arg-Glu", "Gly-His", "Ala-Ser",
"Ala-Thr", "Ala-Trp", "Ala-Tyr", "Ile-Tyr", "Leu-Ala", "Leu-Arg",
"Leu-Gly", "Arg-Ala", "Arg-Arg", "Arg-Asp", "Arg-Gln", "Ala-Asn",
"Ala-Glu", "Ala-Gly", "Ala-His", "Arg-Leu", "Arg-Lys", "Gly-Pro",
"Gly-Ser", "L-Glutamine", "Gln-Gln", "Ile-Arg", "His-Tyr", "Gln-Gly",
"Glu-Asp", "Glu-Glu", "Arg-Met", "Arg-Phe", "Arg-Ser", "Arg-Trp",
"Ala-Ala", "Gly-Lys", "Ala-Leu", "Ala-Lys", "Ala-Phe", "Ala-Arg",
"Gly-Met", "Gly-Gly", "His-Val", "His-Met", "His-Asp", "Gly-Phe",
"His-Gly", "His-Leu", "Val-Ser", "b-Ala-Ala", "b-Ala-Gly", "b-Ala-His",
"Leu-Gly-Gly", "Leu-Leu-Leu", "Phe-Gly-Gly", "Tyr-Gly-Gly", "Phe-Tyr",
"Pro-Glu", "Pro-Ile", "Pro-Lys", "Pro-Ser", "Phe-Asp", "Phe-Glu",
"Gln-Glu", "Phe-Met", "Gly-Gly-Gly", "Phe-Val", "Pro-Arg", "Pro-Asn",
"Gly-D-Ser", "Gly-D-Thr", "Gly-D-Val", "Leu-b-Ala", "D-Ala-Gly",
"Leu-Pro", "Negative Control", "Thr-Phe", "Ser-Glu", "Gly-Asn",
"D-Leu-D-Leu", "D-Ala-Gly-Gly", "Gly-Gly-Phe", "Gly-D-Ala", "Leu-D-Leu",
"Gly-Gly-Ala", "Val-Tyr-Val", "D-Leu-Gly", "D-Leu-Tyr", "Thr-Ser",
"Trp-Val", "Tyr-Ile", "Thr-Asp", "Ser-Gln", "Thr-Gln", "Val-Gln",
"Phe-b-Ala", "Ala-Ala-Ala", "Leu-His", "Val-Ala", "Gly-Asp",
"Gly-Ile", "His-Ala", "His-Glu", "Gly-Gly-D-Leu", "Gly-Gly-Ile",
"Gly-Gly-Leu", "Gly-Phe-Phe", "His-His", "Ile-Asn", "Ile-Leu",
"Leu-Asn", "Ala-Ile", "Ala-Met", "Ala-Val", "Asp-Ala", "Leu-Tyr",
"Lys-Asp", "Val-Phe", "Val-Pro", "L-Glutamine", "Pro-Trp", "Gly-D-Asp",
"g-Glu-Gly", "Pro-Val", "Ser-Asn", "Ser-Asp", "Lys-Gly", "Lys-Met",
"Met-Thr", "Met-Tyr", "Ala-Asp", "Val-Glu", "Asp-Gln", "Asp-Gly",
"Glu-Ala", "Ala-Gln", "Val-Lys", "Tyr-Val", "g-D-Glu-Gly", "D-Ala-Leu",
"Met-b-Ala", "Val-Met", "b-Ala-Phe", "D-Ala-D-Ala", "Chloramphenicol",
"Chloramphenicol", "Chloramphenicol", "Chloramphenicol", "Ofloxacin",
"Ofloxacin", "Ofloxacin", "Ofloxacin", "Minocycline", "Capreomycin",
"Capreomycin", "Capreomycin", "Capreomycin", "Colistin", "Colistin",
"Colistin", "Colistin", "Cephalothin", "Minocycline", "Minocycline",
"Minocycline", "Gentamicin", "Gentamicin", "Gentamicin", "Gentamicin",
"Erythromycin", "Lomefloxacin", "Amikacin", "Cefazolin", "Nafcillin",
"Lincomycin", "Neomycin", "Potassium Tellurite", "Kanamycin",
"Ceftriaxone", "Potassium Tellurite", "Cephalothin", "Kanamycin",
"Neomycin", "Neomycin", "Cefazolin", "Cefazolin", "Cefazolin",
"Nafcillin", "Nafcillin", "Nafcillin", "Enoxacin", "Potassium Tellurite",
"Potassium Tellurite", "Lomefloxacin", "Enoxacin", "Amoxicillin",
"Amoxicillin", "Amoxicillin", "Amoxicillin", "Cephalothin", "Cephalothin",
"Kanamycin", "Kanamycin", "Cloxacillin", "Cloxacillin", "Cloxacillin",
"Cloxacillin", "Chlortetracycline", "Chlortetracycline", "Chlortetracycline",
"Chlortetracycline", "Lomefloxacin", "Lomefloxacin", "Nalidixic Acid",
"Nalidixic Acid", "Amikacin", "Demeclocycline", "Ceftriaxone",
"Ceftriaxone", "Demeclocycline", "Demeclocycline", "Demeclocycline",
"Bleomycin", "Bleomycin", "Bleomycin", "Bleomycin", "Amikacin",
"Enoxacin", "Lincomycin", "Lincomycin", "Lincomycin", "Amikacin",
"Nalidixic Acid", "Enoxacin", "Ceftriaxone", "Neomycin", "Erythromycin",
"Nalidixic Acid", "Erythromycin", "Erythromycin", "Sodium Tungstate",
"Sodium Tungstate", "Sodium Tungstate", "Sodium Tungstate", "Magnesium Chloride",
"Magnesium Chloride", "Magnesium Chloride", "Magnesium Chloride",
"Zinc Chloride", "Copper (II) Chloride", "Copper (II) Chloride",
"Copper (II) Chloride", "Copper (II) Chloride", "Manganese (II) Chloride",
"Manganese (II) Chloride", "Manganese (II) Chloride", "Manganese (II) Chloride",
"Lithium Chloride", "Zinc Chloride", "Zinc Chloride", "Zinc Chloride",
"Sodium Nitrate", "Sodium Nitrate", "Sodium Nitrate", "Sodium Nitrate",
"Sodium Orthovanadate", "Potassium Chloride", "Negative Control",
"Sodium Phosphate", "Iodine", "NaCl", "Potassium Chromate", "Sodium Nitrite",
"Ferric Chloride", "Sodium Pyrophosphate", "Sodium Nitrite",
"Lithium Chloride", "Ferric Chloride", "Potassium Chromate",
"Potassium Chromate", "Sodium Phosphate", "Sodium Phosphate",
"Sodium Phosphate", "Iodine", "Iodine", "Iodine", "Sodium Sulfate",
"Sodium Nitrite", "Sodium Nitrite", "Potassium Chloride", "Sodium Sulfate",
"Ammonium Chloride", "Ammonium Chloride", "Ammonium Chloride",
"Ammonium Chloride", "Lithium Chloride", "Lithium Chloride",
"Ferric Chloride", "Ferric Chloride", "Sodium Selenite", "Sodium Selenite",
"Sodium Selenite", "Sodium Selenite", "NaCl", "NaCl", "NaCl",
"NaCl", "Potassium Chloride", "Potassium Chloride", "Sodium Molybdate Dihydrate",
"Sodium Molybdate Dihydrate", "Negative Control", "Cobalt (II) Chloride",
"Sodium Pyrophosphate", "Sodium Pyrophosphate", "Cobalt (II) Chloride",
"Cobalt (II) Chloride", "Cobalt (II) Chloride", "Calcium Chloride",
"Calcium Chloride", "Calcium Chloride", "Calcium Chloride", "Negative Control",
"Sodium Sulfate", "NaCl", "NaCl", "NaCl", "Negative Control",
"Sodium Molybdate Dihydrate", "Sodium Sulfate", "Sodium Pyrophosphate",
"Potassium Chromate", "Sodium Orthovanadate", "Sodium Molybdate Dihydrate",
"Sodium Orthovanadate", "Sodium Orthovanadate", "Lys-Ala", "Lys-Arg",
"Lys-Asp", "Lys-Glu", "Phe-Ala", "Phe-Asp", "Phe-Glu", "D-Glucose",
"Ile-Gln", "Ile-Leu", "Ile-Met", "Ile-Phe", "Ile-Pro", "His-Val",
"Ile-Ala", "Ile-Arg", "Ile-Asn", "Met-Phe", "Ile-Gly", "Ile-His",
"Ile-Ile", "Met-Arg", "Met-Asp", "Met-Gln", "Met-Glu", "Lys-Lys",
"His-Leu", "Negative Control", "Leu-Glu", "Leu-Arg", "Gly-Ser",
"Lys-Phe", "Met-Leu", "Met-Trp", "Lys-Tyr", "Met-Gly", "Met-Lys",
"Met-Tyr", "Lys-Pro", "Lys-Ser", "Leu-Gly", "Leu-His", "Leu-Ile",
"Leu-Asn", "Leu-Ala", "Leu-Asp", "Leu-Phe", "Met-His", "Met-Ile",
"His-His", "Leu-Met", "Gly-Thr", "Gly-Trp", "Gly-Tyr", "Gly-Val",
"Met-Met", "Met-Pro", "Met-Thr", "Met-Val", "His-Ala", "His-Asp",
"His-Glu", "His-Gly", "Gly-His", "Gly-Ile", "Gly-Leu", "Gly-Lys",
"His-Lys", "His-Met", "Leu-Tyr", "Leu-Val", "Negative Control",
"Ile-Ser", "Lys-Val", "Lys-Thr", "Ile-Trp", "Ile-Tyr", "Ile-Val",
"His-Pro", "His-Ser", "His-Trp", "His-Tyr", "Negative Control",
"Leu-Pro", "Gly-Met", "Gly-Phe", "Gly-Pro", "Gly-Gly", "Leu-Ser",
"Leu-Leu", "Lys-Trp", "Lys-Met", "Lys-Gly", "Leu-Trp", "Lys-Ile",
"Lys-Leu", "Trp-Lys", "Trp-Phe", "Trp-Ser", "Trp-Trp", "Val-Ser",
"Val-Tyr", "Val-Val", "D-Glucose", "Ser-Glu", "Ser-Leu", "Ser-Met",
"Ser-Phe", "Ser-Pro", "Pro-Val", "Ser-Ala", "Ser-Asn", "Ser-Asp",
"Val-Ile", "Ser-Gln", "Ser-Gly", "Ser-His", "Tyr-Tyr", "Tyr-Val",
"Val-Ala", "Val-Arg", "Tyr-Gln", "Pro-Leu", "Negative Control",
"Thr-Gly", "Thr-Asp", "Phe-Val", "Tyr-Gly", "Val-Gln", "Val-Met",
"Tyr-Phe", "Val-Asn", "Val-Gly", "Val-Phe", "Tyr-His", "Tyr-Ile",
"Thr-Leu", "Thr-Met", "Thr-Phe", "Thr-Glu", "Thr-Arg", "Thr-Gln",
"Trp-Ala", "Val-Asp", "Val-Glu", "Pro-Ile", "Thr-Ser", "Pro-Ala",
"Pro-Arg", "Pro-Asn", "Pro-Asp", "Val-His", "Val-Leu", "Val-Lys",
"Val-Pro", "Pro-Glu", "Pro-Gln", "Pro-Gly", "Pro-Hyp", "Phe-Ile",
"Phe-Met", "Phe-Phe", "Phe-Pro", "Pro-Lys", "Pro-Phe", "Trp-Gly",
"Trp-Leu", "Negative Control", "Ser-Ser", "Tyr-Trp", "Tyr-Leu",
"Ser-Tyr", "Ser-Val", "Thr-Ala", "Pro-Pro", "Pro-Ser", "Pro-Trp",
"Pro-Tyr", "Negative Control", "Trp-Arg", "Phe-Ser", "Phe-Trp",
"Phe-Tyr", "Phe-Gly", "Trp-Asp", "Thr-Pro", "Tyr-Lys", "Tyr-Glu",
"Trp-Tyr", "Trp-Glu", "Trp-Val", "Tyr-Ala", "FGF-1 (aFGF)", "FGF-1 (aFGF)",
"FGF-1 (aFGF)", "FGF-1 (aFGF)", "IL-8", "IL-8", "IL-8", "IL-8",
"Leptin", "Gastrin", "Gastrin", "Gastrin", "Gastrin", "Ghrelin",
"Ghrelin", "Leptin", "Leptin", "IL-6", "Leptin", "Leptin", "Leptin",
"IL-1b", "IL-1b", "IL-2", "IL-2", "PDGF-AB", "Glucagon", "Negative Control",
"hGH (Somatotropin)", "Exendin-3", "Insulin", "PDGF-AB", "IL-2",
"IL-6", "IL-1b", "IL-2", "IL-6", "IL-8", "PDGF-AB", "PDGF-AB",
"hGH (Somatotropin)", "hGH (Somatotropin)", "hGH (Somatotropin)",
"Exendin-3", "Exendin-3", "Exendin-3", "IGF-I", "IL-2", "IL-2",
"Glucagon", "hGH (Somatotropin)", "Resistin", "Resistin", "Resistin",
"Resistin", "IL-6", "IL-6", "IL-6", "IL-8", "Resistin", "Resistin",
"Glucagon", "Glucagon", "Negative Control", "Negative Control",
"Insulin", "Insulin", "Glucagon", "Glucagon", "IGF-I", "IGF-I",
"Negative Control", "Gastrin", "IL-1b", "IL-1b", "Gastrin", "Exendin-3",
"Exendin-3", "Ghrelin", "Ghrelin", "Ghrelin", "Ghrelin", "Negative Control",
"IGF-I", "Insulin", "Insulin", "Insulin", "Negative Control",
"IGF-I", "hGH (Somatotropin)", "IL-1b", "PDGF-AB", "FGF-1 (aFGF)",
"IGF-I", "FGF-1 (aFGF)", "PDGF-AB", "Thr-Glu", "Thr-Gly", "Thr-Leu",
"Thr-Met", "Val-Leu", "Val-Tyr", "Val-Val", "g-Glu-Gly", "Phe-Ala",
"Phe-Pro", "Phe-Ser", "Phe-Trp", "Pro-Ala", "Met-Phe", "Met-Pro",
"Met-Trp", "Met-Val", "Val-Arg", "Phe-Gly", "Phe-Ile", "Phe-Phe",
"Tyr-Ala", "Tyr-Gln", "Tyr-Glu", "Tyr-Gly", "Trp-Asp", "Met-Glu",
"Negative Control", "Ser-Ala", "Pro-Phe", "Lys-Phe", "Trp-Gly",
"Tyr-Phe", "Val-Gly", "Trp-Trp", "Tyr-His", "Tyr-Trp", "Val-His",
"Trp-Leu", "Trp-Lys", "Ser-Gly", "Ser-His", "Ser-Leu", "Pro-Pro",
"Pro-Leu", "Pro-Tyr", "Ser-Pro", "Tyr-Leu", "Tyr-Lys", "Met-Gln",
"Ser-Phe", "Lys-Pro", "Lys-Ser", "Lys-Thr", "Lys-Trp", "Tyr-Tyr",
"Val-Asn", "Val-Asp", "Val-Ile", "Lys-Tyr", "Lys-Val", "Met-Arg",
"Met-Asp", "Leu-Val", "Lys-Ala", "Lys-Arg", "Lys-Glu", "Met-Gly",
"Met-His", "Thr-Ala", "Thr-Arg", "L-Glutamine", "Pro-Asp", "Trp-Tyr",
"Trp-Phe", "Pro-Gln", "Pro-Gly", "Pro-Hyp", "Met-Ile", "Met-Leu",
"Met-Lys", "Met-Met", "Leu-Ser", "Ser-Ser", "Lys-Ile", "Lys-Leu",
"Lys-Lys", "Leu-Trp", "Ser-Tyr", "Ser-Met", "Trp-Ser", "Trp-Glu",
"Thr-Pro", "Ser-Val", "Trp-Ala", "Trp-Arg", "pH 9.5 + L-Methionine",
"pH 9.5 + L-Phenylalanine", "pH 9.5 + L-Proline", "pH 9.5 + L-Serine",
"X-b-D-Galactosaminide", "X-a-D-Mannoside", "X-PO4", "X-SO4",
"pH 4.5 + 4-Hydroxy-L-Proline (trans)", "pH 4.5 + Anthranilic Acid",
"pH 4.5 + L-Norleucine", "pH 4.5 + L-Norvaline", "pH 4.5 + D,L-a-Amino-Butyric Acid",
"pH 4.5 + L-Threonine", "pH 4.5 + L-Tryptophan", "pH 4.5 + L-Citrulline",
"pH 4.5 + L-Valine", "X-b-D-Glucoside", "pH 4.5 + L-Ornithine",
"pH 4.5 + L-Homoarginine", "pH 4.5 + L-Homoserine", "pH 9.5 + Cadaverine",
"pH 9.5 + Putrescine", "pH 9.5 + Histamine", "pH 9.5 + b-Phenylethylamine",
"pH 9.5 + L-Valine", "pH 4.5 + L-Isoleucine", "pH 3.5", "pH 9.5",
"pH 4.5 + D,L-Diamino-Pimelic Acid", "pH 10", "pH 9.5 + L-Ornithine",
"pH 9.5 + Urea", "X-a-D-Glucuronide", "pH 9.5 + L-Norvaline",
"pH 9.5 + Tyramine", "X-Caprylate", "X-b-D-Glucuronide", "pH 9.5 + L-Homoarginine",
"pH 9.5 + L-Homoserine", "pH 9.5 + L-Alanine", "pH 9.5 + L-Arginine",
"pH 9.5 + L-Asparagine", "pH 4.5 + Trimethylamine-N-Oxide", "pH 4.5 + 5-Hydroxy-L-Tryptophan",
"pH 4.5 + Urea", "pH 9.5 + L-Glutamine", "pH 9.5 + Creatine",
"pH 9.5 + Trimethylamine-N-Oxide", "pH 4.5 + L-Histidine", "pH 9.5 + L-Glutamic Acid",
"pH 4.5", "pH 4.5 + L-Alanine", "pH 4.5 + L-Arginine", "pH 4.5 + L-Asparagine",
"X-a-D-Glucoside", "X-a-D-Galactoside", "X-b-D-Galactoside",
"X-b-D-Glucosaminide", "pH 4.5 + L-Aspartic Acid", "pH 4.5 + L-Glutamic Acid",
"pH 4.5 + L-Glutamine", "pH 4.5 + Glycine", "pH 5.5", "pH 6",
"pH 7", "pH 8", "pH 4.5 + L-Leucine", "pH 4.5 + L-Lysine", "pH 9.5 + L-Leucine",
"pH 9.5 + L-Lysine", "pH 4", "pH 4.5 + p-Amino-Benzoic Acid",
"pH 9.5 + Agmatine", "pH 9.5 + Anthranilic Acid", "pH 4.5 + L-Cysteic Acid",
"pH 4.5 + D-Lysine", "pH 4.5 + 5-Hydroxy-L-Lysine", "pH 4.5 + L-Methionine",
"pH 4.5 + L-Phenylalanine", "pH 4.5 + L-Proline", "pH 4.5 + L-Serine",
"pH 4.5", "pH 9.5 + Glycine", "pH 8.5", "pH 9", "pH 9.5", "pH 5",
"pH 9.5 + L-Histidine", "pH 9.5 + L-Aspartic Acid", "pH 9.5 + L-Norleucine",
"pH 9.5 + 4-Hydroxy-L-Proline (trans)", "pH 9.5 + L-Threonine",
"pH 9.5 + L-Isoleucine", "pH 9.5 + L-Tryptophan", "pH 9.5 + L-Tyrosine"
), .Dim = c(96L, 42L), .Dimnames = list(c("F01", "F02", "F03",
"F04", "H09", "H10", "H11", "H12", "C09", "D01", "D02", "D03",
"D04", "C05", "C06", "C07", "C08", "H03", "C10", "C11", "C12",
"G05", "G06", "G07", "G08", "F08", "B10", "A01", "E01", "D10",
"A12", "F10", "G12", "H06", "G03", "G09", "H01", "H07", "F11",
"F12", "E02", "E03", "E04", "D11", "D09", "D12", "E07", "G10",
"G11", "B09", "E06", "B01", "B02", "B03", "B04", "H02", "H04",
"H05", "H08", "B05", "B06", "B07", "B08", "A05", "A06", "A07",
"A08", "B11", "B12", "E11", "E12", "A02", "D05", "G04", "G01",
"D06", "D07", "D08", "C01", "C02", "C03", "C04", "A03", "E08",
"A09", "A10", "A11", "A04", "E09", "E05", "G02", "F09", "F05",
"E10", "F06", "F07"), c("PM-M14", "PM24", "PM05", "PM16", "PM14",
"PM21", "PM04", "PM15", "PM-M12", "PM-M01", "PM01", "Gen III",
"PM09", "PM20", "PM23", "PM02", "ECO", "PM17", "PM25", "PM18",
"PM13", "SF-N2", "SF-P2", "PM12", "PM19", "PM22", "PM-M06", "PM-M11",
"PM-M13", "PM-M TOX01", "PM03", "PM-M08", "PM-M02", "PM06", "PM08",
"PM11", "PM-M05", "PM-M03", "PM-M04", "PM-M07", "PM07", "PM10"
)))
